OpenChemistry/avogadrolibs

- avogadro/qtopengl/qttextrenderstrategy.cpp
Fixes issue #9 
Change-Id: I3e8eb996df4f1594a8df3dad5d75f3df571854aa
> Make sure to scale text based on the device pixel ratio (i.e., retina)

- avogadro/qtplugins/editor/editor.cpp
- avogadro/qtplugins/editor/editor.h
Gives the bond distance between the atoms.
Change-Id: Ia26ea632a4a32fd63d6c495f7b74206ca60949d5
> Add distance label while drawing occurs for immediate feedback.

- avogadro/qtplugins/editor/editor.cpp
Automatic hydrogen adjustment isn't ready yet, but at least make the button work.
Change-Id: I0b545d84b274addbc9dc0b49e7275b4e72d7ab3f
> Enable hydrogen addition.

- CMakeLists.txt
- avogadro/io/cjsonformat.cpp
- avogadro/quantumio/nwchemjson.cpp
- boostpython/CMakeLists.txt
- boostpython/core.cpp
- boostpython/io.cpp
- boostpython/main.cpp
Very early initial support, primarily focused on some limited uses for web services at this stage. It is self-contained, and can be moved/removed in future.
> Boost python

- avogadro/qtplugins/openbabel/obprocess.cpp
- avogadro/qtplugins/openbabel/openbabel.cpp
Also, if interpreting output fails be more verbose in the console to
make debugging a little easier.
Change-Id: I316e2e2abb7382dac21d5e9b06b479ff8664c715
> Q_WS* were dropped in Qt5, fixed obabel for Windows

- CMakeLists.txt
Change-Id: I0f1960dbe1c93b557b0d77e42ea21db5e43ac569
> Bumped the version to 0.9.0

- avogadro/core/crystaltools.cpp
This is just to demonstrate that I can submit pull requests...
> Fixed a small misspelling

- avogadro/qtgui/molecule.cpp
- avogadro/qtgui/molecule.h
Make the interface symmetric to assignment operator.
> Provide copy constructor to create Molecule from base class.

- avogadro/core/basisset.h
- avogadro/core/gaussianset.h
- avogadro/core/molecule.cpp
- avogadro/core/slaterset.h
Added a virtual copy constructor to BasisSet so that it may be copied.
> Added a clone function to BasisSet.

- avogadro/core/elementdata.h
Probably needs translations, esp. for element names.
> Update element symbols and names through 118 based on IUPAC

- avogadro/core/avospglib.cpp
- avogadro/core/avospglib.h
- avogadro/qtplugins/CMakeLists.txt
- avogadro/qtplugins/crystal/crystal.cpp
- avogadro/qtplugins/spacegroup/CMakeLists.txt
- avogadro/qtplugins/spacegroup/spacegroup.cpp
- avogadro/qtplugins/spacegroup/spacegroup.h
- tests/core/spglibtest.cpp
Added several spglib functions for crystals
Added space group perception, primitive reduction, and cell conventionalization.
In addition, the user can specify the tolerance for all of these features.
All of the features use spglib to perform them. When performing any action,
the program tells the user what the tolerance is currently set to.
> Spglib functions added

- avogadro/core/molecule.h
- avogadro/qtgui/meshgenerator.cpp
- avogadro/qtgui/meshgenerator.h
- avogadro/qtplugins/quantumoutput/quantumoutput.cpp
- avogadro/qtplugins/quantumoutput/quantumoutput.h
- avogadro/qtplugins/quantumoutput/surfacedialog.cpp
- avogadro/qtplugins/quantumoutput/surfacedialog.h
- avogadro/qtplugins/quantumoutput/surfacedialog.ui
- avogadro/quantumio/gaussiancube.cpp
This doesn't do beta orbitals yet, but I can work on that next.
> Resurrect newui-rendersurfaces

- avogadro/qtplugins/coordinateeditor/coordinateeditordialog.cpp
The atomic editor wasn't working at all for me originally because
movePosition(QTextCursor::NextCharacter) was not moving it to the
end of the line. movePosition(QTextCursor::Down) followed by
movePosition(QTextCursor::StartOfLine) seems to work fine! And I
have it checking to make sure it only moves if it is not at the
end of the document. Additional bug fixes: program no longer freezes
if the user opens up the coordinate editor and hits "enter" or
"return" on a blank document. In addition, the input validator skips
over empty lines - this is helpful if the user deletes some lines but
forgets to delete white space or returns. Finally, I also set it up
so that the undo stack is updated when the coordinates are edited,
and it is now "undo-able."
> Fixed some bugs in the atomic coordinate editor

- avogadro/qtgui/rwmolecule.cpp
- avogadro/qtgui/rwmolecule.h
- avogadro/qtplugins/copypaste/copypaste.cpp
- avogadro/qtplugins/copypaste/copypaste.h
Test by drawing something, performing Cut, then draw something more and paste.
Need to finish off selection for this to be really worthwhile.
> Paste to insert

- avogadro/qtgui/elementdetail_p.cpp
Fixes weird superscript in periodic table
> Qt has redefined macros in Qt5 -> Q_OS_MAC

- avogadro/qtplugins/coordinateeditor/coordinateeditordialog.cpp
- avogadro/qtplugins/crystal/unitcelldialog.cpp
Minor fixes to ensure we execute the right code paths.
> Move our last few Q_WS_ tests to Q_OS_

- avogadro/io/cjsonformat.cpp
As part of the "atoms" dictionary, e.g.
"selected" : [ 1, 1, 0, 0, 0, 0, 0, 0 ]
This will allow input generators and other scripts to get the selected atoms if they want/need them.
> Save and read atom selections to CJSON.

- avogadro/core/molecule.h
- avogadro/qtplugins/bonding/bonding.cpp
- avogadro/qtplugins/manipulator/manipulator.cpp
- avogadro/qtplugins/manipulator/manipulator.h
Add support in various features for selection:
* Bond or unbond only selected atoms
* Move only selected atoms
> Enhance for selections

- avogadro/qtplugins/lineformatinput/lineformatinput.cpp
- avogadro/qtplugins/lineformatinput/lineformatinput.h
- avogadro/qtplugins/lineformatinput/lineformatinputdialog.cpp
- avogadro/qtplugins/lineformatinput/lineformatinputdialog.h
- avogadro/qtplugins/lineformatinput/lineformatinputdialog.ui
Polish dialog box and put into the Build menu.
Might be worth having as an "Import -> From Descriptor" command too?
> Update as "insert from SMILES" commands like Avo1.x

- avogadro/qtplugins/coordinateeditor/coordinateeditor.cpp
- avogadro/qtplugins/customelements/customelements.cpp
- avogadro/qtplugins/hydrogens/hydrogens.cpp
Minor UI adjustments (e.g., standardize the Edit menu with UI guidelines)
> Move to build menu

- avogadro/qtplugins/quantuminput/inputGenerators/apbs.py
- avogadro/qtplugins/quantuminput/inputGenerators/gamessuk.py
- avogadro/qtplugins/quantuminput/inputGenerators/gaussian.py
- avogadro/qtplugins/quantuminput/inputGenerators/inputgeneratortest.py
- avogadro/qtplugins/quantuminput/inputGenerators/molpro.py
- avogadro/qtplugins/quantuminput/inputGenerators/mopac.py
- avogadro/qtplugins/quantuminput/inputGenerators/nwchem.py
- avogadro/qtplugins/quantuminput/inputGenerators/qchem.py
- avogadro/qtplugins/quantuminput/inputGenerators/terachem.py
- avogadro/qtplugins/scriptfileformats/formatScripts/cclibScript.py
- avogadro/qtplugins/scriptfileformats/formatScripts/zyx.py
- avogadro/qtplugins/workflows/scripts/scale.py
- avogadro/qtplugins/workflows/scripts/test.py
I can see additional ways to clean up the scripts, but this is a nice first start.
Once the installer feature is ready, I'd like to move these to separate repositories anyway.
> Clean up Python formatting with autopep8 command

- avogadro/qtplugins/importpqr/pqrrequest.cpp
This code should never have used NULL, but checked for 0 as it is not
dealing with pointers.
Change-Id: If0247a2a00c0bcdcecd3df5573a0df8a7746f2bb
> Fixed compiler error

- avogadro/quantumio/gaussiancube.cpp
Fixes issue for PR https://github.com/OpenChemistry/avogadrolibs/pull/161
> Minor fix to gaussian cube reader

- avogadro/core/molecule.cpp
- avogadro/core/molecule.h
Added move copy constructor and move assignment operator
to the Molecule class.
> Added move semantics to Avogadro::Core::Molecule

- avogadro/qtplugins/quantuminput/CMakeLists.txt
- avogadro/qtplugins/quantuminput/inputGenerators/dalton.py
Does not require C++ changes - instead requests cjson and
marshalls atoms into unique sets based on elements.
> Initial Dalton python script, based on #186

- CMakeLists.txt
(Actually 1.90 is over a year old)
> Bump version number to 1.91 for next release.

- CMakeLists.txt
- avogadro/core/CMakeLists.txt
- cmake/FindLibmsym.cmake
Cleaned up #239 branch, tested.
> Add libmsym check for cmake

- avogadro/core/molecule.cpp
- avogadro/core/molecule.h
This PR adds facility to store timestep values from molecular dynamics trajectories in the molecule class.
> Addition of timestep field in molecule class

- avogadro/io/CMakeLists.txt
- avogadro/io/fileformatmanager.cpp
- avogadro/io/trrformat.cpp
- avogadro/io/trrformat.h
This PR aims at adding support for reading GROMACS trr trajectory files.
> GROMACS trr trajectory support

- avogadro/qtplugins/playertool/playertool.cpp
- avogadro/qtplugins/playertool/playertool.h
> Player tool overhaul

- avogadro/core/molecule.cpp
- avogadro/core/molecule.h
I've completed the function which has been incomplete for quite some time, so that it can be used for conducting checks in each element of the coordinate sets in the tests for trajectory readers.
> Completing coordinate3D() function in molecule class

- avogadro/qtplugins/CMakeLists.txt
- avogadro/qtplugins/plotrmsd/CMakeLists.txt
- avogadro/qtplugins/plotrmsd/plotrmsd.cpp
- avogadro/qtplugins/plotrmsd/plotrmsd.h
This PR adds support for displaying the Root Mean Square Deviation curve for multimolecules. This will be useful for analysing MD trajectories.
> RMSD VTK chart plugin for multimolecules

- avogadro/qtgui/containerwidget.cpp
- avogadro/qtgui/elementdetail_p.cpp
- avogadro/qtgui/filebrowsewidget.cpp
- avogadro/qtgui/fileformatdialog.cpp
- avogadro/qtgui/interfacescript.cpp
- avogadro/qtgui/interfacewidget.cpp
- avogadro/qtgui/pythonscript.cpp
- avogadro/qtgui/rwmolecule.h
https://github.com/KDE/clazy/blob/master/docs/checks/README-qstring-allocations.md
Part of #298
Change-Id: I412195b0d9fc60d26f2116e78b0bbc310fcd197f
> Use clazy fixit for string literals to reduce memory allocs

- avogadro/io/lammpsformat.cpp
- tests/io/CMakeLists.txt
- tests/io/lammpstest.cpp
This PR adds a basic test for LAMMPS reader.
> Basic test for LAMMPS dump

- .github/config.yml
https://github.com/behaviorbot/welcome
Version 1.1
Suite D4700 …
> Add a config for the welcome bot:

- scripts/travis/build.sh
- tests/io/xyztest.cpp
We can add more tests such as this one. However, it looks
like this test may be currently failing.
Version 1.1
Suite D4700
of my knowledge, is covered under an appropriate …
> Travis-CI: Add AvogadroIOTests

- avogadro/qtgui/CMakeLists.txt
- avogadro/qtgui/pythonscript.cpp
- avogadro/qtgui/scriptloader.cpp
- avogadro/qtgui/scriptloader.h
- avogadro/qtplugins/pluginmanager.cpp
- avogadro/qtplugins/quantuminput/quantuminput.cpp
- avogadro/qtplugins/quantuminput/quantuminput.h
- avogadro/qtplugins/scriptfileformats/formatScripts/cclibScript.py
- avogadro/qtplugins/scriptfileformats/formatScripts/zyx.py
- avogadro/qtplugins/scriptfileformats/scriptfileformats.cpp
- avogadro/qtplugins/workflows/scripts/scale.py
- avogadro/qtplugins/workflows/scripts/test.py
- avogadro/qtplugins/workflows/workflow.cpp
- avogadro/qtplugins/workflows/workflow.h
Eliminates duplicate code between different script types
but also gives one place to handle conflict resolution, etc.
> Migrate to a unified Python script loading code.

- avogadro/core/gaussiansettools.cpp
- avogadro/core/gaussiansettools.h
- avogadro/io/cjsonformat.cpp
- avogadro/qtplugins/surfaces/gaussiansetconcurrent.cpp
- avogadro/qtplugins/surfaces/gaussiansetconcurrent.h
- avogadro/qtplugins/surfaces/surfacedialog.cpp
- avogadro/qtplugins/surfaces/surfacedialog.h
- avogadro/qtplugins/surfaces/surfaces.cpp
> Alpha beta

- avogadro/qtgui/interfacescript.cpp
- avogadro/qtgui/interfacewidget.cpp
- avogadro/qtgui/interfacewidget.h
- avogadro/qtplugins/workflows/workflow.cpp
Several key enhancements:
- workflows can have no options (e.g., just flatten already)
- workflows can return data in multiple formats (e.g., xyz)
- fix GUI bug where the dialog would continually show old dialogs
Version 1.1
Suite D4700
(b) The contribution is based upon previous work that, …
> Enhance workflow scripts

- avogadro/io/pdbformat.cpp
This PR adds support for reading PDB trajectory files using the recently added PDB reader.
****
Version 1.1
Suite D4700 …
> Trajectory support in PDB reader

- avogadro/qtplugins/openbabel/CMakeLists.txt
- avogadro/qtplugins/openbabel/obfileformat.cpp
> OBFileFormat: Allow processing of extra args

- .travis.yml
- scripts/travis/build.sh
- scripts/travis/install.sh
Version 1.1
Suite D4700
work with …
> Add a default Mac build to the Travis script.

- README.md
Signed-off-by: Marcus D. Hanwell <marcus.hanwell@kitware.com>
> Minor updates to the README text

- .circleci/config.yml
- .travis.yml
- requirements-dev.txt
- scripts/appveyor/upload-pypi.ps1
- scripts/circleci/upload_pypi.sh
- scripts/travis/build.sh
- scripts/travis/install.sh
> Always run binary wheel build on CircleCi

- CMakeLists.txt
This release may be a little unusual, largely targeting the library and
testing the automatic build/upload of binary Python wheels. Once that is
working also plan on getting an updated application release/binaries
ready.
> Bump the version in preparation for release

- python/core.cpp
- python/io.cpp
Before adding more, settle on a Pythonic style for the wrapped API.
> Pythonify the Avogadro API exposed

- avogadro/core/gaussiansettools.cpp
- avogadro/core/gaussiansettools.h
- python/core.cpp
> Expose calculateElectronDensity and calculateSpinDensity to python

- avogadro/core/avospglib.h
- avogadro/core/cube.h
- avogadro/core/gaussianset.h
- avogadro/core/gaussiansettools.h
- avogadro/core/molecule.h
- avogadro/core/slaterset.h
- avogadro/io/fileformat.h
- avogadro/io/mmtfformat.h
- avogadro/io/vaspformat.h
- avogadro/protocall/moleculedeserializer.h
- avogadro/qtgui/molecule.h
- avogadro/qtgui/periodictableview.h
- avogadro/qtplugins/pluginmanager.h
- avogadro/rendering/arrowgeometry.h
- avogadro/rendering/cylindergeometry.h
- avogadro/rendering/textproperties.h
Signed-off-by: Yuri Chornoivan <yurchor@ukr.net>
Version 1.1
Suite D4700 …
> Fix minor Doxygen issues

- avogadro/core/vector.h
- avogadro/qtplugins/ballandstick/ballandstick.cpp
- avogadro/qtplugins/selectiontool/selectiontool.cpp
- avogadro/qtplugins/selectiontool/selectiontool.h
- avogadro/rendering/drawable.cpp
- avogadro/rendering/drawable.h
- avogadro/rendering/geometrynode.cpp
- avogadro/rendering/geometrynode.h
- avogadro/rendering/glrenderer.cpp
- avogadro/rendering/glrenderer.h
- avogadro/rendering/spheregeometry.cpp
- avogadro/rendering/spheregeometry.h
- avogadro/rendering/spheres_fs.glsl
This now works for area selection, with some keyboard modifiers for growing a selection and toggling it. Some more improvements can be made to look and feel, but I think this will be a big improvement for most people.
> Area selection

- avogadro/io/gromacsformat.cpp
Resolves https://github.com/OpenChemistry/avogadrolibs/issues/345
The gro reader as of now guesses the element name from the atom name and sets a CustomElementMap, which can be quite ambiguous at times (eg. HG** is considered as Mercury instead of Hydrogen). This patch attempts to fix the issue, by obtaining the atomic numbers from residuedata.
--------
Version 1.1
Suite D4700 …
> Assigning atoms in gro input reader based on residue data

- .github/workflows/build_cmake.yml
- avogadro/quantumio/nwchemjson.cpp
Version 1.1
Suite D4700
work with …
> First attempt at a GitHub qt build workflow

- avogadro/qtplugins/playertool/CMakeLists.txt
- cmake/AvogadroLibsConfig.cmake.in
- thirdparty/libgwavi/CMakeLists.txt
> Add fedora patches

- avogadro/qtgui/CMakeLists.txt
- tests/qtgui/CMakeLists.txt
Thanks to Drew Parsons for the bug report
Version 1.1
Suite D4700 …
> Switch all references to Py2 to 3, fixing #431

- .github/workflows/clang-format-check.yml
- avogadro/qtplugins/importpqr/importpqr.cpp
Version 1.1
Suite D4700
work with …
> New attempt at a clang-format-diff using apt-get

- .github/workflows/misspell-fixer.yml
Version 1.1
Suite D4700
work with …
> Automated spelling pull-requests are annoying

- avogadro/qtplugins/coloropacitymap/CMakeLists.txt
- avogadro/qtplugins/qtaim/CMakeLists.txt
- avogadro/qtplugins/resetview/CMakeLists.txt
- avogadro/qtplugins/surfaces/CMakeLists.txt
This fixes the shared plugin build for me locally.
> Missing plugin links

- avogadro/qtplugins/qtaim/qtaimcubature.cpp
- avogadro/qtplugins/qtaim/qtaimlsodaintegrator.cpp
- avogadro/qtplugins/qtaim/qtaimodeintegrator.cpp
Not always great options, but these are error paths
Version 1.1
Suite D4700 …
> Remove exit calls from qtaim code

- avogadro/core/molecule.cpp
- avogadro/core/molecule.h
- tests/qtgui/moleculetest.cpp
Signed-off-by: dvermd <315743+dvermd@users.noreply.github.com>
Version 1.1
Suite D4700
work with …
> Add centerOfGeometry, centerOfMass and radius methods on Molecule

- avogadro/qtplugins/copypaste/copypaste.cpp
Version 1.1
Suite D4700
work with …
> Add support for only clearing selected atoms

- avogadro/core/molecule.cpp
- avogadro/core/molecule.h
- tests/qtgui/moleculetest.cpp
> Add bestFitPlane on Molecule

- avogadro/qtplugins/plugindownloader/downloaderwidget.cpp
- avogadro/qtplugins/plugindownloader/downloaderwidget.h
- avogadro/qtplugins/plugindownloader/plugindownloader.cpp
> Improved download widget

- avogadro/qtplugins/editor/editor.cpp
- avogadro/qtplugins/measuretool/measuretool.cpp
Version 1.1
Suite D4700
work with …
> Adjust font size for 2D measure labels on hires screens

- avogadro/qtplugins/symmetry/symmetryscene.cpp
- avogadro/qtplugins/symmetry/symmetryutil.cpp
- avogadro/qtplugins/symmetry/symmetrywidget.cpp
> Symmetry enhancements

- avogadro/io/cmlformat.cpp
Should replce PR#486
Version 1.1
Suite D4700
license and I have the right under that license to submit …
> Fix #483 through stream-specific locale

- avogadro/qtplugins/openbabel/openbabel.cpp
https://discuss.avogadro.cc/t/cant-open-a-cif-file-in-avogadro/3447/10
Version 1.1
Suite D4700
license …
> Add some debugging to see if we can work out Mac OB issue

- avogadro/qtplugins/playertool/playertool.cpp
- thirdparty/gif-h/gif.h
Fixes #569 - movies were created with 2x too small width/height
Bump gif.h
Version 1.1
Suite D4700 …
> Make sure to check movie sizes for high-dpi screens

- avogadro/io/hdf5dataformat.h
- avogadro/io/xyzformat.h
- avogadro/qtgui/toolplugin.h
- avogadro/qtplugins/ballandstick/ballandstick.h
- avogadro/qtplugins/editor/editor.h
- avogadro/qtplugins/manipulator/manipulator.h
- avogadro/qtplugins/molecularproperties/molecularpropertiesdialog.h
- avogadro/qtplugins/navigator/navigator.h
- avogadro/qtplugins/quantuminput/quantuminput.h
Version 1.1
Suite D4700
work with …
> Fix author name

- avogadro/qtplugins/plugindownloader/downloaderwidget.cpp
- avogadro/qtplugins/plugindownloader/downloaderwidget.ui
- avogadro/qtplugins/plugindownloader/plugindownloader.cpp
- avogadro/qtplugins/plugindownloader/plugindownloader.h
- avogadro/qtplugins/plugindownloader/zipextracter.cpp
- avogadro/qtplugins/plugindownloader/zipextracter.h
> Fix downloader file extraction + look-and-feel

- avogadro/qtplugins/coordinateeditor/coordinateeditor.cpp
- avogadro/qtplugins/coordinateeditor/coordinateeditor.h
- avogadro/qtplugins/coordinateeditor/coordinateeditordialog.cpp
- avogadro/qtplugins/coordinateeditor/coordinateeditordialog.h
Fixes PR#394
Version 1.1
Suite D4700
work …
> Switch to the navigate tool after pasting coordinates over empty

- avogadro/qtgui/extensionplugin.h
- avogadro/qtgui/toolplugin.h
- avogadro/qtplugins/copypaste/copypaste.cpp
- avogadro/qtplugins/pluginfactory.h
- cmake/avogadroplugin.cpp.in
Seems like ctor code is called now
(not sure about dtor)
Version 1.1
Suite D4700 …
> Make sure extension plugins have parents

- avogadro/qtplugins/copypaste/copypaste.cpp
> Copypaste selections

- avogadro/qtplugins/editor/editor.cpp
Fixes #484
Version 1.1
Suite D4700
work …
> Change the bond order when dragging between existing atoms

- .github/workflows/build_cmake.yml
Currently sets the release to draft / prerelease to be safe
Version 1.1
Suite D4700 …
> Add release actions if a revision is tagged

- CMakeLists.txt
Version 1.1
Suite D4700
work with …
> Bump version for 1.94 release

- i18n/af.po
- i18n/ar.po
- i18n/id.po
- i18n/it.po
- i18n/pt_BR.po
- i18n/sq.po
- i18n/sr.po
- i18n/tr.po
Version 1.1
Suite D4700
work with …
> Fix some merge conflicts with Weblate

- avogadro/core/CMakeLists.txt
- avogadro/core/angleiterator.cpp
- avogadro/core/angleiterator.h
- avogadro/core/angletools.h
- avogadro/core/dihedraliterator.cpp
- avogadro/core/dihedraliterator.h
- avogadro/qtplugins/measuretool/measuretool.cpp
- avogadro/qtplugins/measuretool/measuretool.h
> Implement iterators

- .github/workflows/build_cmake.yml
Version 1.1
Suite D4700
work with …
> Make sure to grab (and fix) libinchi too

- avogadro/qtplugins/openbabel/obprocess.cpp
- avogadro/qtplugins/openbabel/obprocess.h
- avogadro/qtplugins/openbabel/openbabel.cpp
- avogadro/qtplugins/openbabel/openbabel.h
Version 1.1
Suite D4700
work with …
> Add support for reading partial charge models from obabel

- avogadro/qtplugins/select/select.cpp
- avogadro/qtplugins/select/select.h
> More selection commands

- .github/workflows/build_cmake.yml
Saves downloading again, extracting, compile, etc.
Version 1.1
Suite D4700 …
> Try to cache build/thirdparty directory

- avogadro/qtplugins/CMakeLists.txt
- avogadro/qtplugins/applycolors/CMakeLists.txt
- avogadro/qtplugins/applycolors/applycolors.cpp
- avogadro/qtplugins/applycolors/applycolors.h
Applies colors by index and reset colors for atoms
Currently, no partial charges, so to be done later
Version 1.1
Suite D4700 …
> New View => Apply Colors menu

- avogadro/qtopengl/qttextrenderstrategy.cpp
- avogadro/qtplugins/bondcentrictool/bondcentrictool.cpp
- avogadro/qtplugins/editor/editor.cpp
- avogadro/qtplugins/measuretool/measuretool.cpp
> Improve textrender

- avogadro/qtplugins/insertfragment/insertfragment.cpp
- avogadro/qtplugins/insertfragment/insertfragment.h
- avogadro/qtplugins/insertfragment/insertfragmentdialog.cpp
- avogadro/qtplugins/insertfragment/insertfragmentdialog.h
Version 1.1
Suite D4700
work with …
> Add back support for importing crystals

- avogadro/qtplugins/insertfragment/insertfragment.cpp
- avogadro/qtplugins/insertfragment/insertfragment.h
Fix issue with insert fragment + import crystal sequentially
HT @drew-parsons
Version 1.1
Suite D4700 …
> Create separate dialogs for crystals and fragments

- .github/workflows/build_cmake.yml
Version 1.1
Suite D4700
work with …
> Cache downloads to save time, minimize network issues

- avogadro/core/CMakeLists.txt
- avogadro/core/residue.cpp
- avogadro/core/residue.h
- avogadro/core/secondarystructure.cpp
- avogadro/core/secondarystructure.h
- avogadro/io/mmtfformat.cpp
- avogadro/io/pdbformat.cpp
> Get secondary structure

- avogadro/core/molecule.cpp
- avogadro/core/molecule.h
- avogadro/core/residuecolors.h
- avogadro/qtplugins/applycolors/applycolors.cpp
- avogadro/qtplugins/applycolors/applycolors.h
- By chain
- By secondary structure
- By amino acid
- By amino using "shapely" scheme
Version 1.1
Suite D4700 …
> Add commands and color schemes for residues

- avogadro/qtplugins/copypaste/copypaste.cpp
Version 1.1
Suite D4700
work with …
> Fix "delete last atom" bug

- .github/release-drafter.yml
Should help automate the release drafter action
Version 1.1
Suite D4700 …
> Add "autolabel" regex for bug / build changes

- avogadro/core/residue.h
- avogadro/qtplugins/applycolors/applycolors.cpp
- avogadro/qtplugins/cartoons/cartoons.cpp
- avogadro/qtplugins/cartoons/cartoons.h
- avogadro/qtplugins/selectiontool/selectiontool.cpp
- avogadro/rendering/beziergeometry.cpp
- avogadro/rendering/beziergeometry.h
- avogadro/rendering/bsplinegeometry.cpp
- avogadro/rendering/bsplinegeometry.h
- avogadro/rendering/cartoongeometry.cpp
- avogadro/rendering/cartoongeometry.h
- avogadro/rendering/curvegeometry.cpp
- avogadro/rendering/curvegeometry.h
- avogadro/rendering/spheregeometry.cpp
- avogadro/rendering/spheregeometry.h
- Added area hit (area selection) in all curves geometry.
- Fix visual bug where the curve has big twists. 
- Added complex/simple cartoon with arrows.
Version 1.1
Suite D4700
(b) The contribution is based upon previous work …
> Improve in cartoon display

- avogadro/qtgui/layermodel.cpp
Version 1.1
Suite D4700
work with …
> Start Layer 1 for the user-visible model

- .github/workflows/clang-tidy.yml
Version 1.1
Suite D4700
work with …
> Try adding clazy (KDE checker) to static analysis

- avogadro/qtplugins/ballandstick/ballandstick.cpp
- avogadro/qtplugins/ballandstick/ballandstick.h
Version 1.1
Suite D4700
work with …
> Add sliders for atom and bond scales

- avogadro/io/cjsonformat.cpp
Version 1.1
Suite D4700
work with …
> Fix crash in CJSON reading file without labels

- avogadro/io/cjsonformat.cpp
Version 1.1
Suite D4700
work with …
> Fix reading residues from CJSON including sec struct support

- avogadro/io/mmtfformat.cpp
Version 1.1
Suite D4700
work with …
> Fix a crash with 1qlz (check new bonds have correct atom index)

- avogadro/qtplugins/resetview/resetview.cpp
Fix the problem with the center camera function. 
The major errors were: no normalize the covariance (non-orthogonal axis), approximate the center using the `getBB` instead of project the points and force the goal matrix instead of the final interpolation (big final jump glitch).
This solves the problem with 'Center' in #684 .
Version 1.1
Suite D4700
(a) The contribution …
> Fix odd behavior on 'Center'

- avogadro/qtplugins/label/label.cpp
- avogadro/qtplugins/label/label.h
Version 1.1
Suite D4700
work with …
> Add a color button to customize labels

- avogadro/qtplugins/cartoons/cartoons.cpp
Version 1.1
Suite D4700
work with …
> Continue rendering cartoons even if residues aren't found

- avogadro/core/layermanager.cpp
- avogadro/qtgui/pluginlayermanager.cpp
- avogadro/qtplugins/ballandstick/ballandstick.cpp
- avogadro/qtplugins/ballandstick/ballandstick.h
- avogadro/qtplugins/cartoons/cartoons.h
I've added default enable for cartoons and Ball and stick. And some minor fixes with qsettings.
Version 1.1
Suite D4700 …
> Default value in fresh install

- .github/workflows/clang-tidy.yml
Version 1.1
Suite D4700
work with …
> Remove clazy action - not working right now

- .github/workflows/update-i18n-templates.yml
Version 1.1
Suite D4700
work with …
> Minor tweaks to the automated pull request

- .github/workflows/build_cmake.yml
Version 1.1
Suite D4700
work with …
> Try linuxdeployqt for an AppImage build again

- avogadro/qtplugins/3dmol/3dmol.cpp
- avogadro/qtplugins/bondcentrictool/bondcentrictool.cpp
- avogadro/qtplugins/editor/editor.cpp
- avogadro/qtplugins/label/labeleditor.cpp
- avogadro/qtplugins/manipulator/manipulator.cpp
- avogadro/qtplugins/measuretool/measuretool.cpp
- avogadro/qtplugins/navigator/navigator.cpp
- avogadro/qtplugins/playertool/playertool.cpp
- avogadro/qtplugins/quantuminput/quantuminput.cpp
- avogadro/qtplugins/selectiontool/selectiontool.cpp
Version 1.1
Suite D4700
work with …
> Add tooltips to tools

- avogadro/core/angletools.h
Fixes #801
Version 1.1
Suite D4700
work …
> Fall back to Wikipedia method for dihedral angles

- avogadro/core/molecule.cpp
I'm sorry, I didn't expect #829 to be merged right away. Here are the additional changes that you had requested in that Pull Request's conversation, in case you want to add them.
Version 1.1
Suite D4700 …
> Perform requested changes to previous PR

- avogadro/core/molecule.cpp
- avogadro/io/mdlformat.cpp
- avogadro/io/pdbformat.cpp
Version 1.1
Suite D4700
work with …
> Try to fix the broken wheels. Windows complains about std::array

- .github/workflows/codacy.yml
- avogadro/io/lammpsformat.cpp
- avogadro/qtgui/pythonscript.cpp
- avogadro/qtplugins/plugindownloader/zipextracter.cpp
- thirdparty/libgwavi/gwavi.c
- thirdparty/pugixml/pugiconfig.hpp
- thirdparty/pugixml/pugixml.cpp
- thirdparty/pugixml/pugixml.hpp
Version 1.1
Suite D4700
work with …
> Create Codacy scans

- scripts/github-actions/install.sh
Should allow more modern CMake usage #866
Version 1.1
Suite D4700 …
> Try to install Eigen on Windows and Ubuntu

- avogadro/core/CMakeLists.txt
- avogadro/core/molecule.cpp
- avogadro/core/neighborperceiver.cpp
- avogadro/core/neighborperceiver.h
This implements a new class, which moves the new binning logic from `perceiveBondsSimple` out of there and exposes it in a generic way. Possible uses include:
- Regular bond perception, which has already been updated to use the new code.
- Intermolecular force detection.
- Surface generation.
The new interface offers a few advantages:
- Does not assume anything about the data it's passed. Can be used for atoms or other data that can be represented as points in space.
- Is very fast. Time to construct an instance is O(n) to number of points, and time to get neighbors of some arbitrary point is O(n) to number of neighbors.
- Can handle any point as input, not necessarily the ones in the given set, or even within bounds.
Developer …
> Implement close contact perception logic

- avogadro/qtplugins/meshes/meshes.cpp
- avogadro/qtplugins/meshes/meshes.h
Fixes #872
Version 1.1
Suite D4700
work …
> Add an initial config widget to set colors and opacity

- avogadro/rendering/CMakeLists.txt
- avogadro/rendering/mesh_fs.glsl
- avogadro/rendering/mesh_opaque_fs.glsl
- avogadro/rendering/meshgeometry.cpp
- avogadro/rendering/meshgeometry.h
Gives a more conventional look with some specular shine
Version 1.1
Suite D4700 …
> Tweak the mesh lighting .. now lights "from the top"

- .github/workflows/build_cmake.yml
- cmake/BuildType.cmake
- cmake/CompilerFlags.cmake
Version 1.1
Suite D4700
work with …
> Add tests using various sanitizers

- .github/workflows/build_cmake.yml
Version 1.1
Suite D4700
work with …
> Make sure to sign and notarize the Mac DMG after build

- avogadro/qtplugins/CMakeLists.txt
- avogadro/qtplugins/closecontacts/CMakeLists.txt
- avogadro/qtplugins/closecontacts/closecontacts.cpp
- avogadro/qtplugins/closecontacts/closecontacts.h
- avogadro/rendering/CMakeLists.txt
- avogadro/rendering/dashedline_fs.glsl
- avogadro/rendering/dashedline_vs.glsl
- avogadro/rendering/dashedlinegeometry.cpp
- avogadro/rendering/dashedlinegeometry.h
> Render close contacts

- avogadro/io/vaspformat.h
- avogadro/molequeue/inputgenerator.cpp
- avogadro/qtgui/interfacescript.cpp
- avogadro/rendering/arrowgeometry.h
> Fix minor compile warnings

- CMakeLists.txt
Version 1.1
Suite D4700
work with …
> Bump for version 1.96 release

- .github/workflows/build_cmake.yml
Version 1.1
Suite D4700
work with …
> Fix error when notarizing Mac DMG - use the right working dir

- avogadro/io/fileformatmanager.cpp
- avogadro/io/fileformatmanager.h
Should solve https://discuss.avogadro.cc/t/open-fchk-file/3860/2
Version 1.1
Suite D4700
license and I …
> Add case-insensitive lookup for file extensions

- .github/workflows/codacy.yml
- scripts/github-actions/filter_sarif.py
Version 1.1
Suite D4700
work with …
> Start to filter Codacy warnings (e.g., remove MISRA)

- .github/workflows/add_artifact_urls.yml
- .github/workflows/build_cmake.yml
- .github/workflows/build_m1.yml
> Build Mac M1 binaries on self-hosted runner

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- STYLE.md
Version 1.1
Suite D4700
work with …
> Clean up some bits with markdown lint [skip ci]

- avogadro/core/atomutilities.cpp
- avogadro/core/bond.h
- avogadro/io/pdbformat.cpp
- avogadro/qtgui/hydrogentools.cpp
- avogadro/qtplugins/bondcentrictool/bondcentrictool.cpp
- avogadro/qtplugins/bondcentrictool/bondcentrictool.h
> Use getOtherAtom everywhere it makes sense

- avogadro/rendering/dashedlinegeometry.cpp
> Enable GL_LINE_SMOOTH in DashedLineGeometry

- avogadro/qtplugins/commandscripts/command.cpp
Prevents duplicate English menus appearing
Version 1.1
Suite D4700 …
> Make sure to translate menu paths for Python scripts.

- avogadro/qtgui/layermodel.cpp
- avogadro/qtplugins/cartoons/cartoons.h
- avogadro/qtplugins/closecontacts/closecontacts.h
- avogadro/qtplugins/licorice/licorice.h
- avogadro/qtplugins/molecularproperties/molecularproperties.cpp
- avogadro/qtplugins/molecularproperties/molecularproperties.h
- avogadro/qtplugins/molecularproperties/molecularpropertiesdialog.cpp
- avogadro/qtplugins/molecularproperties/molecularpropertiesdialog.h
- avogadro/qtplugins/wireframe/wireframe.h
> Fix several i18n problems

- i18n/pt.po
Version 1.1
Suite D4700
work with …
> Fix errors in pt translation file [skip ci]

- avogadro/qtplugins/noncovalent/noncovalent.cpp
The performance issue bugging me lately was due to a std::any_of calling the copy constructor of the captured molecule on every lambda call. Never again... Also, I've introduced code to avoid the loop altogether for disabled atoms, and other small tweaks.
The overall performance increase is at least about 30x on my machine. That is, bonds are now shown "instantly" again.
Version 1.1
Suite D4700
By making a contribution to this project, I …
> Optimize non-covalent perception, code cleanup

- avogadro/qtplugins/editor/editor.h
- avogadro/qtplugins/editor/editortoolwidget.cpp
- avogadro/qtplugins/editor/editortoolwidget.h
Fix #962
Version 1.1
Suite D4700
work with …
> Translate editor element list

- avogadro/core/cube.cpp
- avogadro/core/cube.h
- avogadro/qtplugins/surfaces/surfacedialog.cpp
- avogadro/qtplugins/surfaces/surfaces.cpp
- avogadro/qtplugins/surfaces/surfaces.h
> Implement Solvent Excluded Surfaces

- avogadro/qtgui/hydrogentools.cpp
Fixes the issue mentioned in #979.
Version 1.1
Suite D4700 …
> Fix incorrect hydrogen geometries

- .github/workflows/build_m1.yml
Version 1.1
Suite D4700
work with …
> Fix notarization for Mac M1 builds

- avogadro/qtgui/periodictableview.cpp
Fixes typing lower case elements "n" = "N"
Fixes #963
Version 1.1
Suite D4700 …
> Add arrow key navigation of the periodic table

- avogadro/core/mesh.cpp
For a protein like `1aco`, the total mesh generation time goes down about 4x. I have also been able to generate the surface for a whole ribosome without getting an OOM kill (14 GB of physical memory used, though).
Version 1.1
Suite D4700
(b) …
> Optimize mesh smoothing

- .github/workflows/build_m1.yml
Version 1.1
Suite D4700
work with …
> Add more debugging to notarization step

- .github/workflows/build_m1.yml
Version 1.1
Suite D4700
work with …
> More work to debug m1 notarization

- avogadro/core/cube.cpp
- avogadro/core/cube.h
- avogadro/io/cjsonformat.cpp
- avogadro/qtplugins/apbs/opendxreader.cpp
- avogadro/qtplugins/coloropacitymap/coloropacitymap.cpp
- avogadro/quantumio/gaussiancube.cpp
- avogadro/vtk/vtkglwidget.cpp
- python/core.cpp
> Use float within Cube instead of double

- avogadro/qtplugins/scriptcharges/CMakeLists.txt
- avogadro/qtplugins/scriptcharges/chargeScripts/antechamber.py
Version 1.1
Suite D4700
work with …
> Add AM1-BCC charges using antechamber

- avogadro/qtplugins/scriptcharges/chargeScripts/antechamber.py
Version 1.1
Suite D4700
work with …
> Use single-point calculation for AM1-BCC with Antechamber

- avogadro/qtplugins/bondcentrictool/bondcentrictool.cpp
Fixes #1000
Version 1.1
Suite D4700
work …
> When finding connected atoms, only ignore rings containing the bond

- avogadro/qtplugins/propertytables/propertymodel.cpp
- avogadro/qtplugins/propertytables/propertymodel.h
- Atoms
Version 1.1
Suite D4700
work with …
> Enable editing of some properties

- avogadro/qtplugins/select/select.cpp
- avogadro/qtplugins/select/select.h
Version 1.1
Suite D4700
work with …
> Add select water, enlarge selection and shrink selection

- avogadro/qtplugins/openbabel/obcharges.cpp
- avogadro/qtplugins/scriptcharges/scriptchargemodel.cpp
Should fix #1009
Version 1.1
Suite D4700 …
> Make sure to cache partial charges from obabel or scripts

- avogadro/io/CMakeLists.txt
- avogadro/io/fileformatmanager.cpp
- avogadro/io/turbomoleformat.cpp
- avogadro/io/turbomoleformat.h
Fix #1004
Version 1.1
Suite D4700
work …
> Implement support for Turbomole coord format (also used by xtb)

- avogadro/qtplugins/select/select.cpp
Version 1.1
Suite D4700
work with …
> Make sure to also select isolated "O" as part of HOH residues

- avogadro/core/residue.cpp
- avogadro/core/residue.h
- avogadro/qtplugins/select/select.cpp
- avogadro/qtplugins/select/select.h
Version 1.1
Suite D4700
work with …
> Add "select backbone" and "select sidechain" commands

- avogadro/qtplugins/closecontacts/closecontacts.cpp
- avogadro/qtplugins/closecontacts/closecontacts.h
An interface similar to that of `noncovalent`, but without an angle tolerance setting.
Version 1.1
Suite D4700 …
> Add tabbed interface to Close Contacts plugin

- avogadro/qtplugins/fetchpdb/fetchpdb.cpp
- avogadro/qtplugins/insertfragment/insertfragment.cpp
- avogadro/qtplugins/networkdatabases/networkdatabases.cpp
Version 1.1
Suite D4700
work with …
> Fix some menu priorities for file import/export

- avogadro/qtplugins/select/select.cpp
- avogadro/qtplugins/surfaces/surfaces.cpp
> Fix segfaults in Surfaces and Select Backbone

- avogadro/qtgui/layermodel.cpp
Fix #1032
Version 1.1
Suite D4700
work …
> Fix crash when layer names are translated (hu_HU right now)

- CMakeLists.txt
Version 1.1
Suite D4700
work with …
> Update for 1.97.0 release number

- avogadro/molequeue/client/jsonrpcclient.cpp
- avogadro/qtplugins/cp2kinput/cp2kinputdialog.ui
- avogadro/qtplugins/insertdna/insertdna.cpp
- avogadro/qtplugins/lammpsinput/lammpsinputdialog.ui
- avogadro/qtplugins/openmminput/openmminputdialog.ui
- avogadro/qtplugins/propertytables/propertymodel.cpp
- docs/contrib/index.rst
- docs/scripts/formats.rst
- docs/scripts/interface.rst
Signed-off-by: Eisuke Kawashima <e-kwsm@users.noreply.github.com>
Version 1.1
Suite D4700
work with …
> fix typos and punctuation inconsistency (... vs …)

- avogadro/io/pdbformat.cpp
> Add AltLoc support to PDB importer

- .github/workflows/build_m1.yml
Version 1.1
Suite D4700
work with …
> Tweak for M1 5.15.5 from homebrew [skip-ci]

- avogadro/io/mmtfformat.cpp
- tests/io/mmtftest.cpp
Includes a new testcase for this support, which requires [this PR](https://github.com/OpenChemistry/avogadrodata/pull/12).
Version 1.1
Suite D4700
of my knowledge, is covered …
> Add AltLoc support to MMTF importer

- avogadro/qtplugins/propertytables/propertyview.cpp
Version 1.1
Suite D4700
work with …
> Fix bug selecting incorrect angle and torsion atoms

- avogadro/core/molecule.cpp
- avogadro/core/molecule.h
- avogadro/io/cjsonformat.cpp
- avogadro/qtgui/interfacescript.cpp
- avogadro/quantumio/gamessus.cpp
- avogadro/quantumio/gaussianfchk.cpp
- avogadro/quantumio/gaussianfchk.h
> Add default spin multiplicity methods

- avogadro/qtplugins/surfaces/CMakeLists.txt
Thanks to @Antikapitalista
Version 1.1
Suite D4700 …
> Fix linking to calc module

- avogadro/qtplugins/bonding/bonding.cpp
- avogadro/qtplugins/centroid/centroid.cpp
- avogadro/qtplugins/coordinateeditor/coordinateeditor.cpp
- avogadro/qtplugins/copypaste/copypaste.cpp
- avogadro/qtplugins/hydrogens/hydrogens.cpp
- avogadro/qtplugins/insertdna/insertdna.cpp
- avogadro/qtplugins/insertfragment/insertfragment.cpp
- avogadro/qtplugins/lineformatinput/lineformatinput.cpp
Version 1.1
Suite D4700
work with …
> Fix some Edit and Build menu priorities

- avogadro/qtplugins/molecularproperties/molecularproperties.cpp
- avogadro/qtplugins/propertytables/propertytables.cpp
- avogadro/qtplugins/symmetry/symmetry.cpp
Previously had "Angle" above "Atom" which was confusing
Version 1.1
Suite D4700 …
> Fix properties menu priorities

- avogadro/qtplugins/templatetool/templatetoolwidget.ui
Version 1.1
Suite D4700
work with …
> Switch "denticity" for "type"

- .github/dependabot.yml
Should flag security and other action updates
Version 1.1
Suite D4700 …
> Add Dependabot update checks for GitHub actions

- avogadro/qtplugins/propertytables/propertymodel.cpp
Version 1.1
Suite D4700
work with …
> Fix bug to allow editing atom formal charges

- .github/workflows/misspell-fixer.yml
- avogadro/qtplugins/importpqr/pqrrequest.cpp
- avogadro/qtplugins/importpqr/pqrrequest.h
- avogadro/qtplugins/openmminput/openmminputdialog.cpp
- avogadro/qtplugins/selectiontool/selectiontool.cpp
Fix #1106 - also some very minor spelling changes
Version 1.1
Suite D4700 …
> Don't "apply layer" if layer is already zero

- avogadro/io/cjsonformat.cpp
- avogadro/qtplugins/molecularproperties/molecularpropertiesdialog.cpp
- avogadro/qtplugins/molecularproperties/molecularpropertiesdialog.ui
Version 1.1
Suite D4700
work with …
> Grab the "markup" name from the PubChem JSON response

- avogadro/qtgui/rwmolecule.cpp
- avogadro/qtplugins/editor/editor.cpp
Also make sure to retain unique id for batch adjustment.
Fix #678 in my testing
Version 1.1
Suite D4700 …
> Make sure to add / adjust valence in the correct order

- .github/workflows/build_cmake.yml
Should fix problems with out-of-date Python packages
Version 1.1
Suite D4700 …
> Update to latest version of install-qt-action

- avogadro/qtplugins/molecularproperties/molecularpropertiesdialog.cpp
- avogadro/qtplugins/molecularproperties/molecularpropertiesdialog.h
- avogadro/qtplugins/molecularproperties/molecularpropertiesdialog.ui
Version 1.1
Suite D4700
work with …
> Add a copy button for molecular properties

- avogadro/qtplugins/editor/editor.cpp
Version 1.1
Suite D4700
work with …
> Pick a contrasting color (vs. the background) for the text

- avogadro/io/mmtfformat.cpp
- avogadro/qtplugins/fetchpdb/fetchpdb.cpp
Prevents crash and fix #1125 - present a dialog instead
Version 1.1
Suite D4700 …
> Catch exceptions thrown by mmtf:decode

- avogadro/io/cjsonformat.cpp
Fix #1109
Version 1.1
Suite D4700
work …
> If the file is empty, return early

- avogadro/qtopengl/CMakeLists.txt
- avogadro/qtopengl/glwidget.cpp
- avogadro/qtplugins/CMakeLists.txt
- avogadro/qtplugins/bondcentrictool/CMakeLists.txt
- avogadro/qtplugins/coloropacitymap/CMakeLists.txt
- avogadro/qtplugins/coloropacitymap/histogramwidget.cpp
- avogadro/qtplugins/editor/CMakeLists.txt
- avogadro/qtplugins/label/CMakeLists.txt
- avogadro/qtplugins/manipulator/CMakeLists.txt
- avogadro/qtplugins/measuretool/CMakeLists.txt
- avogadro/qtplugins/meshes/meshes.cpp
- avogadro/qtplugins/navigator/CMakeLists.txt
- avogadro/qtplugins/resetview/CMakeLists.txt
- avogadro/qtplugins/selectiontool/CMakeLists.txt
- avogadro/qtplugins/surfaces/CMakeLists.txt
- avogadro/qtplugins/svg/CMakeLists.txt
- avogadro/qtplugins/templatetool/CMakeLists.txt
- avogadro/rendering/CMakeLists.txt
- avogadro/rendering/avogadrorendering.h
- avogadro/rendering/curvegeometry.cpp
- avogadro/rendering/cylindergeometry.cpp
- avogadro/rendering/glrenderer.cpp
- avogadro/rendering/glrenderer.h
- avogadro/rendering/solid_first_fs.glsl
- avogadro/rendering/solid_vs.glsl
- avogadro/rendering/solidpipeline.cpp
- avogadro/rendering/solidpipeline.h
- avogadro/rendering/spheregeometry.cpp
- avogadro/vtk/vtkglwidget.h
> Screen space shading

- avogadro/qtgui/jsonwidget.cpp
Fixes #1124 and fixes #1052
Version 1.1
Suite D4700 …
> Fix bug with "combined rows" like Theory / Basis set

- avogadro/qtplugins/cartoons/cartoons.cpp
This is what many people want, so provide one set of polygons
Version 1.1
Suite D4700 …
> By default only enable regular cartoons

- avogadro/CMakeLists.txt
Version 1.1
Suite D4700
work with …
> Turn off deprecated declarations (e.g., Qt 5.15)

- avogadro/qtgui/jsonwidget.cpp
- avogadro/qtgui/jsonwidget.h
Version 1.1
Suite D4700
work with …
> Put charge / spin in one line with two labels

- avogadro/io/pdbformat.cpp
Version 1.1
Suite D4700
work with …
> Add uncommon "ent" extension for PDB entries

- avogadro/qtplugins/meshes/meshes.cpp
- avogadro/qtplugins/surfaces/surfaces.cpp
Version 1.1
Suite D4700
work with …
> Fix rendering bug that dropped half of the MO rendering

- avogadro/io/pdbformat.cpp
- avogadro/qtplugins/coloropacitymap/coloropacitymap.cpp
- avogadro/qtplugins/coloropacitymap/coloropacitymap.h
> Fix colormap vtk action

- avogadro/qtgui/fileformatdialog.cpp
For #1118
Version 1.1
Suite D4700
work …
> Fix mis-translated export dialog

- avogadro/qtplugins/copypaste/copypaste.cpp
- avogadro/qtplugins/copypaste/copypaste.h
Fix #1104
Version 1.1
Suite D4700
work …
> Add back copy as SMILES / InChI

- avogadro/rendering/solid_first_fs.glsl
> Mitigate bright edges in SSAO

- avogadro/qtgui/layermodel.cpp
- avogadro/qtgui/layermodel.h
Profiling found a surprising amount of time loading icons...
Version 1.1
Suite D4700 …
> Make sure to cache icons for the LayerModel

- avogadro/qtplugins/editor/editor.cpp
With this change, the drag is smooth by fixing a logic error.
Version 1.1
Suite D4700 …
> Fix editor smooth drag

- avogadro/qtplugins/networkdatabases/networkdatabases.cpp
Version 1.1
Suite D4700
work with …
> Fix requests to the NIH resolver to use new scheme

- avogadro/rendering/solid_first_fs.glsl
- avogadro/rendering/solidpipeline.cpp
- avogadro/rendering/solidpipeline.h
Version 1.1
Suite D4700
work with …
> Tweak the edge detection to allow changing the strength too

- .github/workflows/build_cmake.yml
- avogadro/io/pdbformat.cpp
Reported by teslim on the forum:
https://discuss.avogadro.cc/t/avogadro-quit-unexpectedly/3953/5
Version 1.1
Suite D4700 …
> Fix crash reading non-standard PDB file

- avogadro/core/molecule.cpp
For example caffeine, it wouldn't find all the bonds
(basically, try setting *one* bond and then you can set all)
Version 1.1
Suite D4700
of my knowledge, is covered …
> Fix some cases where bond order perception gave up

- avogadro/qtgui/layermodel.cpp
- avogadro/qtplugins/qtaim/qtaimengine.h
- avogadro/qtplugins/qtaim/qtaimextension.cpp
Version 1.1
Suite D4700
work with …
> Turn off request for QTAIM rendering option

- avogadro/calc/chargemodel.h
- avogadro/io/fileformat.h
- avogadro/io/hdf5dataformat.h
- avogadro/molequeue/inputgenerator.h
- avogadro/qtgui/colorbutton.h
- avogadro/qtgui/interfacescript.h
- avogadro/qtgui/jsonwidget.cpp
- avogadro/qtgui/pluginlayermanager.h
- avogadro/qtplugins/coloropacitymap/vtkChartHistogram.cpp
- avogadro/qtplugins/coordinateeditor/coordinateeditordialog.cpp
- avogadro/qtplugins/qtaim/qtaimcubature.cpp
- avogadro/qtplugins/scriptfileformats/fileformatscript.h
- avogadro/qtplugins/selectiontool/selectiontool.cpp
- avogadro/quantumio/gaussianfchk.h
- avogadro/rendering/cartoongeometry.cpp
- avogadro/rendering/cartoongeometry.h
- avogadro/rendering/sphere_ao_bake_fs.glsl
- avogadro/rendering/sphere_ao_bake_vs.glsl
- avogadro/rendering/textlabelbase.cpp
- avogadro/rendering/textlabelbase_vs.glsl
- avogadro/rendering/texture2d.h
- cmake/CompilerFlags.cmake
- scripts/extractrc.sh
- tests/core/moleculetest.cpp
- tests/qtgui/moleculetest.cpp
- thirdparty/gif-h/gif.h
- thirdparty/libgwavi/gwavi.c
- thirdparty/nlohmann/detail/input/binary_reader.hpp
- thirdparty/nlohmann/detail/output/binary_writer.hpp
- thirdparty/tinycolormap/include/tinycolormap.hpp
> chore: fix typos and spelling inconsistency

- avogadro/qtplugins/editor/editor.cpp
Check "adjust hydrogens" - if so, remove them before the atom https://discuss.avogadro.cc/t/hydrogen-not-removed/4420
Version 1.1
Suite D4700 …
> When removing an atom, remove bonded hydrogens if needed

- avogadro/qtplugins/editor/editor.cpp
> When deleting an atom, adjust the hydrogens of the neighbors

- .github/workflows/codeql.yml
Version 1.1
Suite D4700
work with …
> Another try at a CodeQL scanning workflow

- avogadro/qtgui/backgroundfileformat.h
> [skip ci] Fix a spelling issue in a header

- .github/workflows/add_clang_tidy.yml
- .github/workflows/misspell-fixer.yml
Check for artifact and quit early if it doesn't exist
Version 1.1
Suite D4700
work with …
> Posting clang-tidy results would sometimes fail

- SECURITY.md
Add a security policy since GH is making this prominent in their new redesign.
> Create SECURITY.md [skip-ci]

- .github/workflows/build_wheels.yml
- avogadro/CMakeLists.txt
- pyproject.toml
- python/CMakeLists.txt
- scripts/github-actions/install.sh
Just to note right now I am fixing up the Python build, but the wheels will need more updates to the manylinux base images, there was a custom Linux image, just digging into some of those details. This does allow a development build to compile/work with Python now and supports build in a subdirectory of the source tree.
> Python build and wheels

- avogadro/CMakeLists.txt
- python/CMakeLists.txt
- setup.py
This took a while to track down, but this reliably fixes the macos wheels in my testing and the others all keep working too. See commit messages, but a small change in the right place 😄
> Python module

- avogadro/rendering/povrayvisitor.cpp
> Fix #1179 (finally) setting the colors and transparency of MO

- avogadro/qtplugins/bonding/bonding.cpp
- avogadro/qtplugins/bonding/bonding.h
> Add an action to create a bond between selected atoms

- avogadro/core/angletools.h
> Switch to (fixed) faster dihedral formula

- avogadro/qtplugins/coordinateeditor/coordinateeditordialog.cpp
> Fix #1317 - editor wasn't using the format specification for parsing

- avogadro/qtplugins/label/label.cpp
> Cleanup label serialize, fixing a potential crash

- avogadro/qtgui/extensionplugin.h
- avogadro/qtgui/toolplugin.h
- avogadro/qtplugins/spectra/spectra.cpp
- avogadro/qtplugins/spectra/spectra.h
Previous code would ignore the signals, sent before the app connected
Version 1.1
Suite D4700
work …
> Fixup mechanism to register script commands - now called by the app

- .github/codeql-config.yml
> Restrict scanning to ignore thirdparty and auto-generated code

- avogadro/qtplugins/surfaces/surfaces.cpp
- avogadro/quantumio/CMakeLists.txt
- avogadro/quantumio/gamessus.cpp
- avogadro/quantumio/genericoutput.cpp
- avogadro/quantumio/genericoutput.h
- avogadro/quantumio/nwchemlog.cpp
- avogadro/quantumio/orca.cpp
Needs a bit more testing, but works okay for now
Version 1.1
Suite D4700 …
> Add a generic output reader - use internal, then cclib, then OB

- avogadro/qtplugins/templatetool/templatetool.cpp
- avogadro/qtplugins/templatetool/templatetoolwidget.cpp
> Enable clipboard insertion for ligands

- avogadro/qtplugins/insertfragment/insertfragmentdialog.cpp
- avogadro/qtplugins/insertfragment/insertfragmentdialog.h
- avogadro/qtplugins/insertfragment/insertfragmentdialog.ui
> Add a preview panel when PNG images are present for molecules

- avogadro/qtplugins/crystal/crystal.cpp
- avogadro/qtplugins/crystal/crystal.h
- avogadro/qtplugins/spacegroup/spacegroup.cpp
- avogadro/qtplugins/spacegroup/spacegroup.h
> Add initial crystal and space group commands, including fillUnitCell

- avogadro/qtplugins/bonding/bonding.cpp
- avogadro/qtplugins/bonding/bonding.h
> Add script command to create or remove bonding

- avogadro/qtplugins/resetview/resetview.cpp
- avogadro/qtplugins/resetview/resetview.h
> Add alignView script command (e.g., for screenshots)

- avogadro/qtplugins/openbabel/openbabel.cpp
> Switch to using CJSON as the default format with obabel

- avogadro/core/dihedraliterator.cpp
Regarding  issue #1346 
Version 1.1
Suite D4700
work with modifications, whether created in whole or …
> !valid always returns false and hence is unnecessary

- avogadro/io/trrformat.cpp
regarding #1346 
Version 1.1
Suite D4700 …
> made changes in trrformat.cpp

- avogadro/qtplugins/surfaces/surfacedialog.cpp
- avogadro/qtplugins/surfaces/surfacedialog.ui
- Should no longer add MO / EDens items multiple times
- Should no longer add orbitals multiple times
- Cleaned up the UI grid
- Hides "frame" components unless the molecule a trajectory
Version 1.1
Suite D4700
of my …
> Fix a few UI / UX issues in the surface dialog

- avogadro/qtplugins/selectiontool/selectiontoolwidget.cpp
Fix #1206 - layer is not created by default
Fix #1192 - layer is not changed, avoiding a crash
Version 1.1
Suite D4700 …
> Fix spurious "change layer" bug with the selection tool

- avogadro/qtgui/interfacescript.cpp
> Add command script path to just select atoms

- CMakeLists.txt
- SECURITY.md
> Bump version number for pending 1.98.0 release

- avogadro/qtplugins/forcefield/forcefield.cpp
- avogadro/quantumio/orca.cpp
> Remove a few debugging statements

- CMakeLists.txt
> Bump version number to 1.98.1 for bugfix

- avogadro/io/cjsonformat.cpp
> Add support for Hall number and space group to CJSON read/write

- i18n/en_AU.po
- i18n/en_CA.po
> [no-ci] Update Australian and Canadian localization from GB version

- avogadro/qtplugins/coordinateeditor/coordinateeditordialog.ui
- avogadro/qtplugins/cp2kinput/cp2kinputdialog.ui
- avogadro/qtplugins/gamessinput/gamessinputdialog.ui
- avogadro/qtplugins/lammpsinput/lammpsinputdialog.ui
- avogadro/qtplugins/openmminput/openmminputdialog.ui
- avogadro/qtplugins/plugindownloader/downloaderwidget.ui
- avogadro/qtplugins/surfaces/surfacedialog.ui
Version 1.1
Suite D4700
work with …
> [no-ci] Fix a few remaining cases of .. instead of ellipsis character

- avogadro/qtgui/sortfiltertreeproxymodel.cpp
> Don't show PNG files in the filter dialog

- avogadro/qtgui/jsonwidget.cpp
Thanks to the forum for reporting
Version 1.1
Suite D4700
work with modifications, whether created in …
> Fix empty window showing up for commands without an option dialog

- avogadro/qtplugins/navigator/navigator.cpp
- avogadro/qtplugins/navigator/navigator.h
> Add support for navigator commands - rotate, translate, zoom

- avogadro/core/molecule.cpp
- avogadro/core/molecule.h
- avogadro/qtgui/interfacescript.cpp
- avogadro/qtgui/molecule.h
- avogadro/qtplugins/openbabel/obfileformat.cpp
- avogadro/qtplugins/spectra/spectra.cpp
- avogadro/qtplugins/spectra/spectra.h
- avogadro/qtplugins/surfaces/surfaces.cpp
- avogadro/qtplugins/surfaces/surfaces.h
> Allow scripts to add properties (orbitals, vibrations, cubes)

- avogadro/core/gaussiansettools.cpp
- avogadro/qtplugins/surfaces/gaussiansetconcurrent.cpp
Fix #1480 and the bug report on the forum:
https://discuss.avogadro.cc/t/visualize-electron-density-from-orca-molden-file/3750
Version 1.1
Suite D4700
license and I …
> Generate the density matrix if needed for the electron density surface

- avogadro/qtgui/jsonwidget.cpp
- avogadro/qtgui/jsonwidget.h
> Add a "text" option for scripts to add text labels / help

- avogadro/qtplugins/commandscripts/command.cpp
> Check script --menupath for {} priority numbers

- avogadro/qtplugins/propertytables/CMakeLists.txt
- avogadro/qtplugins/propertytables/propertymodel.cpp
> If no partial charges are assigned, set them

- avogadro/qtgui/jsonwidget.cpp
Fix #1498
Version 1.1
Suite D4700
by me, …
> If userOptions specifies an order, use that to sort the form

- avogadro/qtplugins/coloropacitymap/coloropacitymap.cpp
- avogadro/qtplugins/coloropacitymap/coloropacitymap.h
> Turn off Color Opacity Map unless a VTK widget is active

- avogadro/qtplugins/propertytables/propertyview.cpp
- avogadro/qtplugins/propertytables/propertyview.h
#1505
Version 1.1
Suite D4700
by me, …
> Added copy and export feature to property tables

- avogadro/qtplugins/templatetool/templatetool.cpp
- avogadro/qtplugins/templatetool/templatetoolwidget.cpp
- avogadro/qtplugins/templatetool/templatetoolwidget.h
- avogadro/qtplugins/templatetool/templatetoolwidget.ui
Fixes #1496
Version 1.1
Suite D4700
by …
> Split ligands and functional groups in the template tool

- avogadro/qtplugins/propertytables/propertyview.cpp
- avogadro/qtplugins/templatetool/templatetoolwidget.ui
Version 1.1
Suite D4700
work with …
> Fix two minor ... for translations

- avogadro/qtplugins/insertfragment/insertfragment.cpp
> [skip ci] Insert fragment => Insert molecule by popular request

- .github/workflows/build_cmake.yml
Should address #1443
Version 1.1
Suite D4700
work with modifications, whether created in whole or in …
> Fix Mac builds

- avogadro/qtplugins/forcefield/forcefield.cpp
Fix #1525
Version 1.1
Suite D4700
by me, …
> Fix crash in forcefields - check if method is valid before using it

- .github/workflows/build_wheels.yml
> Upgrading to upload / download v4 broke wheel builds

- avogadro/qtplugins/meshes/meshes.cpp
- avogadro/qtplugins/propertytables/propertyview.h
- avogadro/qtplugins/spacegroup/spacegroup.h
- avogadro/qtplugins/surfaces/surfacedialog.cpp
- avogadro/qtplugins/surfaces/surfaces.cpp
> Fix density color crash

- avogadro/qtplugins/apbs/apbsdialog.cpp
Corresponding translations also need to be modified.
https://hosted.weblate.org/translate/avogadro/avogadrolibs/en/?&offset=339#comments
Version 1.1
Suite D4700 …
> Correct typo

- avogadro/core/gaussiansettools.cpp
- avogadro/quantumio/gaussianfchk.cpp
> Fix quantum surface max cutoff for diffuse functions

- avogadro/core/graph.cpp
> Fixed crash with angle properties on an empty molecule

- .github/workflows/build_qt6.yml
- .github/workflows/clang-format-check.yml
> Fixup workflows

- avogadro/qtplugins/configurepython/CMakeLists.txt
- avogadro/qtplugins/configurepython/condadialog.cpp
- avogadro/qtplugins/configurepython/condadialog.h
- avogadro/qtplugins/configurepython/condadialog.ui
- avogadro/qtplugins/configurepython/configurepython.cpp
- avogadro/qtplugins/configurepython/configurepython.h
- avogadro/qtplugins/configurepython/configurepythondialog.cpp
- avogadro/qtplugins/configurepython/configurepythondialog.h
> Add support for first launch dialog and conda environments

- avogadro/qtgui/toolplugin.h
- avogadro/qtplugins/aligntool/aligntool.cpp
- avogadro/qtplugins/aligntool/aligntool.h
- avogadro/qtplugins/bondcentrictool/bondcentrictool.cpp
- avogadro/qtplugins/bondcentrictool/bondcentrictool.h
- avogadro/qtplugins/editor/editor.cpp
- avogadro/qtplugins/editor/editor.h
- avogadro/qtplugins/label/labeleditor.cpp
- avogadro/qtplugins/label/labeleditor.h
- avogadro/qtplugins/manipulator/manipulator.cpp
- avogadro/qtplugins/manipulator/manipulator.h
- avogadro/qtplugins/measuretool/measuretool.cpp
- avogadro/qtplugins/measuretool/measuretool.h
- avogadro/qtplugins/navigator/navigator.cpp
- avogadro/qtplugins/navigator/navigator.h
- avogadro/qtplugins/playertool/playertool.cpp
- avogadro/qtplugins/playertool/playertool.h
- avogadro/qtplugins/selectiontool/selectiontool.cpp
- avogadro/qtplugins/selectiontool/selectiontool.h
- avogadro/qtplugins/templatetool/templatetool.cpp
- avogadro/qtplugins/templatetool/templatetool.h
This will need a change to avogadroapp for theming but works now
Version 1.1
Suite D4700
work with …
> Update tool plugins to set icon as light / dark theme

- avogadro/qtplugins/forcefield/forcefield.cpp
- avogadro/qtplugins/openbabel/openbabel.cpp
> Only use the obmm interface as a backup - prefer Python scripts

- avogadro/qtplugins/plugindownloader/downloaderwidget.cpp
Fix to use AppLocalDataLocation
Version 1.1
Suite D4700
work with modifications, whether created in …
> Standardize plugin location based on forum feedback

- avogadro/qtplugins/forcefield/forcefield.cpp
- avogadro/qtplugins/forcefield/obenergy.cpp
The new Python energy scripts are preferred
- more flexible (e.g., Open Babel or RDKit)
- can use requirements via pip / conda
Version 1.1
Suite D4700
license and I …
> Based on feedback, only use OB (library) or obmm if no Python

- CMakeLists.txt
- SECURITY.md
> Bump build to 1.99.0 for release

- avogadro/qtplugins/centroid/centroid.cpp
https://discuss.avogadro.cc/t/the-issue-of-empty-molecule-still-exists-in-avogadro-1-99v/5285
Version 1.1
Suite D4700 …
> Fix crash from centroids with empty molecule

- avogadro/qtplugins/select/select.cpp
> Fixed Select Bugs from forum

- .github/workflows/build_wheels.yml
- avogadro/io/cjsonformat.cpp
If a script adds atoms or bonds, but not layers, it's skipped
Version 1.1
Suite D4700
work with …
> Fix crash when reading cjson with invalid layer data

- avogadro/io/pdbformat.cpp
Fixes #1637
Version 1.1
Suite D4700
by …
> Fix crash with short TER record

- avogadro/qtplugins/fetchpdb/fetchpdb.cpp
Should fix #1616
Version 1.1
Suite D4700 …
> Add more error checking for Fetch PDB

- avogadro/qtopengl/glwidget.cpp
https://discuss.avogadro.cc/t/feature-request-animation-tool-should-behave-like-navigation-tool/5347
Version 1.1
Suite D4700 …
> Default tool wasn't set properly, so rotations, etc. ignored

- avogadro/qtplugins/spectra/spectradialog.ui
Fixes #1677
Version 1.1
Suite D4700
by …
> Clarify line width / size in spectra dialog

- .github/workflows/build_m1.yml
> Make sure to grab updated fragments and crystals for m1 mac builds

- avogadro/qtplugins/forcefield/forcefield.cpp
Signed-off-by: Perminder Singh [permindersingh089@gmail.com](mailto:permindersingh089@gmail.com)
issue : #1660 
Version 1.1
Suite D4700 …
> App crashes when clicking "Optimize Geometry" without any atom

- avogadro/io/cjsonformat.cpp
> Add support for reading and writing atom force vectors

- avogadro/io/xyzformat.cpp
Thanks to brockdyer03
https://discuss.avogadro.cc/t/opening-trajectory-files/5570/11
Version 1.1
Suite D4700 …
> Fix XYZ trajectories - prevent final frame with 0,0,0 coords

- avogadro/rendering/solidpipeline.cpp
> Turn off default depth blur, shadows, edge for speed

- avogadro/qtplugins/plugindownloader/downloaderwidget.cpp
https://discuss.avogadro.cc/t/plugin-downloader-error/6384
Version 1.1
Suite D4700
work with …
> Prevent a possible unhandled exception from parsing JSON

- avogadro/qtplugins/plugindownloader/downloaderwidget.cpp
> Fix plugin downloader

- avogadro/qtgui/rwmolecule.cpp
- avogadro/qtplugins/applycolors/applycolors.cpp
- avogadro/qtplugins/select/select.cpp
> Fix a few ellipsis inconsistencies

- .github/workflows/build_cmake.yml
> Switch AppImage build to use the new linuxdeploy tool

- .github/workflows/flatpak.yml
> Add flatpak workflow for GitHub Actions

- .github/workflows/flatpak.yml
> Use Flatpak of flatpak-builder so that we use latest build

- .github/workflows/build_cmake.yml
> Try Windows test signing with SignPath

- .github/workflows/build_cmake.yml
> Test Windows signing with SignPath

- .github/workflows/build_cmake.yml
- .github/workflows/build_windows.yml
- CMakeLists.txt
> Add a separate Windows build for SignPath signing

- .github/workflows/build_windows.yml
> Check the build directory for the final signed artifact

- avogadro/qtplugins/templatetool/templatetool.cpp
> Click to insert a fragment would leave dummy atoms

- avogadro/io/xyzformat.cpp
- tests/io/xyztest.cpp
> Add decimal precision as per forum debate (10 decimals)

- avogadro/quantumio/orca.cpp
> Parse CHELPG charges from Orca output too

- avogadro/qtplugins/configurepython/configurepythondialog.cpp
- look for micromamba and mamba not just conda
- select the current choice when opening the dialog
- properly display the version e.g. (3.11.8)
Version 1.1
Suite D4700 …
> Improve python selection dialog

- avogadro/io/mdlformat.cpp
- avogadro/qtplugins/molecularproperties/molecularmodel.cpp
Also adds superscript radical indicators to the formula
Version 1.1
Suite D4700
work with …
> Read radicals from SDF / Molfile

- avogadro/io/cjsonformat.cpp
- avogadro/qtgui/jsonwidget.cpp
Next step is using it in input generators
Version 1.1
Suite D4700
work with modifications, whether …
> Parse inputParameters if present in cjson

- avogadro/qtplugins/propertytables/propertymodel.cpp
e.g., MMFF94 Partial Charge or Gasteiger Partial Charge
Version 1.1
Suite D4700
work with …
> Make sure to indicate the type of partial charge model

- avogadro/core/bond.h
- avogadro/qtgui/rwmolecule.cpp
- avogadro/qtgui/rwmolecule.h
- avogadro/qtgui/rwmolecule_undo.h
- avogadro/qtplugins/label/label.cpp
- avogadro/qtplugins/label/label.h
- avogadro/qtplugins/propertytables/propertymodel.cpp
- avogadro/qtplugins/propertytables/propertymodel.h
Also render support for bond length and custom labels
Version 1.1
Suite D4700
work with …
> Add support for atom and bond labels in the property tables

- avogadro/qtplugins/spectra/spectra.cpp
- avogadro/qtplugins/spectra/spectradialog.cpp
- avogadro/qtplugins/spectra/spectradialog.h
- avogadro/qtplugins/spectra/spectradialog.ui
- avogadro/quantumio/orca.cpp
> Improve spectra plots, including UV, CD and NMR

- avogadro/qtplugins/plugindownloader/downloaderwidget.cpp
File ended in a newline, which triggered an over-sensitive test
Version 1.1
Suite D4700
work with …
> Fix for problem accessing plugin list

- avogadro/qtplugins/spectra/spectradialog.cpp
> [skip ci] Add B, P, O NMR shift defaults

- avogadro/qtplugins/centroid/centroid.cpp
Fix #1657
Fix #1664
Version 1.1
Suite D4700
work with modifications, whether created in whole or in …
> Tweak the centroid commands

- avogadro/qtplugins/forcefield/obenergy.cpp
- avogadro/qtplugins/forcefield/obenergy.h
- avogadro/qtplugins/forcefield/obmmenergy.cpp
- avogadro/qtplugins/forcefield/obmmenergy.h
Should ensure there's always something better than Lennard-Jones
Version 1.1
Suite D4700
work with …
> Allow ions for all Open Babel force fields and radicals for UFF

- avogadro/qtplugins/editor/editor.cpp
Fix #1478
- remove a hydrogen if right-clicked (always)
- adjust hydrogens if you right-click to break a bond
Version 1.1
Suite D4700 …
> Tweak atom and bond removal

- .github/workflows/clang-format-check.yml
> [skip-ci] Update clang-format check

- avogadro/quantumio/orca.cpp
Ensure orbital reordering is handled correctly
Fixes https://discuss.avogadro.cc/t/molecular-orbitals-displayed-incorrectly/6675?u=ghutchis As reported by forum user chem.os
Version 1.1
Suite D4700
of my knowledge, is covered …
> Fix a bug with parsing ORCA orbital coefficients

- avogadro/qtplugins/templatetool/templatetool.cpp
Should solve future problems since the "atom normal" is often last
Version 1.1
Suite D4700
work with …
> Fix code for haptic ligands. Pick the furthest dummy to attach

- avogadro/core/crystaltools.cpp
> Remove bonds before wrapping atoms to the unit cell

- avogadro/qtplugins/forcefield/forcefield.cpp
- avogadro/qtplugins/forcefield/obenergy.cpp
- avogadro/qtplugins/forcefield/obmmenergy.cpp
> Added more defensive programming in the forcefield code

- avogadro/qtgui/scriptloader.cpp
> Fix plugin menu entry behaviour

- avogadro/qtplugins/configurepython/configurepython.cpp
Thanks to @brockdyer03 for pointing this out on the forum
Version 1.1
Suite D4700
work with …
> Tweak search for Python paths - make sure to check it exists

- avogadro/io/mdlformat.cpp
- avogadro/qtplugins/label/label.cpp
Also when custom data is set, always show the label
Version 1.1
Suite D4700 …
> Handle SDF data blocks better, including from QupKake

- tests/io/CMakeLists.txt
- tests/io/fuzztest.cpp
> Add some initial fuzz IO tests

- CMakeLists.txt
- SECURITY.md
> Bump build to 1.100.0 for release

- avogadro/io/cjsonformat.cpp
- avogadro/io/cmlformat.cpp
- avogadro/io/mdlformat.cpp
- avogadro/io/pdbformat.cpp
- avogadro/io/xyzformat.cpp
- tests/io/fileformatmanagertest.cpp
> Harden file readers (from fuzz tests)

- avogadro/qtplugins/molecularproperties/molecularproperties.cpp
- avogadro/qtplugins/propertytables/propertytables.cpp
- avogadro/qtplugins/qtaim/qtaimextension.cpp
- avogadro/qtplugins/spectra/spectra.cpp
- avogadro/qtplugins/surfaces/orbitals.cpp
- avogadro/qtplugins/surfaces/surfaces.cpp
- avogadro/qtplugins/symmetry/symmetry.cpp
- avogadro/qtplugins/vibrations/vibrations.cpp
> Rename Analysis menu to imperative Analyze to match others

- avogadro/qtplugins/surfaces/surfaces.cpp
- avogadro/rendering/glrenderer.cpp
> Fix translucent surface culling

- README.md
> Update readme to reflect current build workflows

- avogadro/qtgui/customelementdialog.ui
Fixes #1987
Modified the "Rename Elements" window to be scrollable.
Version 1.1
Suite D4700
work with …
> Fix bug with Rename Elements window

- avogadro/io/xyzformat.cpp
> Add support for "allxyz" from Orca - trajectory files

- avogadro/io/xyzformat.cpp
Version 1.1
Suite D4700
work with …
> Fix reading Chemeleon exyz files with no quotes around the Lattice

- avogadro/qtplugins/editor/editor.cpp
Fixes #1997
If you click on a hydrogen, change the bond length If adjust hydrogens is set, change the bond length (ignoring H)
Version 1.1
Suite D4700
license and I …
> When clicking to change an element, tweak the bond length too

- avogadro/qtplugins/manipulator/manipulator.cpp
- avogadro/qtplugins/manipulator/manipulator.h
Thanks to @Nyama on the forum for the report.
Version 1.1
Suite D4700 …
> Fix bug with manual rotations around axes

- avogadro/qtgui/molecule.cpp
- avogadro/qtgui/molecule.h
- avogadro/qtgui/moleculemodel.cpp
- avogadro/qtplugins/molecularproperties/molecularmodel.cpp
> Update the molecule UI list to include richtext formulas

- .github/workflows/build_linux.yml
> Use system eigen when building for Linux (inc. AppImage)

- .github/workflows/build_cmake.yml
- .github/workflows/clang-format-check.yml
> Tweaks to clang-format workflow

- avogadro/io/cjsonformat.cpp
> fix(cjson): fix properties parsing

- avogadro/qtplugins/editor/editor.cpp
> Fix crash on Linux when deleting non-hydrogen atoms

- avogadro/qtplugins/cp2kinput/cp2kinputdialog.cpp
- avogadro/qtplugins/cp2kinput/cp2kinputdialog.h
#1701
Version 1.1
Suite D4700
by me, …
> improve cp2kinput

- avogadro/qtplugins/editor/editor.cpp
> Fix a bug when changing the bond order atoms wouldn't move properly

- avogadro/core/unitcell.h
> fix(wrapFractional): fix comparison

- avogadro/quantumio/orca.cpp
> Tweaks to parse ORCA 6.1 output

- avogadro/qtplugins/cp2kinput/cp2kinputdialog.ui
- avogadro/qtplugins/gamessinput/gamessinputdialog.ui
> chore(input): reduce singleStep

- avogadro/qtplugins/crystal/unitcelldialog.cpp
#2089
TODO
Version 1.1
Suite D4700
by …
> fix(Unit Cell Editor): reject modification of cell and fractional matrices if singular

- avogadro/calc/uff.cpp
- avogadro/core/contrastcolor.h
- avogadro/qtplugins/surfaces/surfaces.cpp
- avogadro/rendering/shaderprogram.cpp
> refactor: use std::clamp (C++17)

- i18n/ca@valencia.po
- i18n/id.po
- i18n/ja.po
- i18n/sk.po
> Fix remaining merge conflicts

- avogadro/qtplugins/bondcentrictool/bondcentrictool.cpp
- avogadro/qtplugins/propertytables/propertytables.cpp
> chore: fix typos

- avogadro/calc/uff.cpp
- avogadro/core/crystaltools.cpp
- avogadro/qtplugins/qtaim/qtaimlsodaintegrator.cpp
- avogadro/qtplugins/qtaim/qtaimmathutilities.cpp
- avogadro/qtplugins/qtaim/qtaimodeintegrator.cpp
- avogadro/qtplugins/svg/svg.cpp
- avogadro/rendering/plyvisitor.cpp
- avogadro/rendering/vrmlvisitor.cpp
> refactor: use hypot

- avogadro/core/molecule.cpp
- avogadro/core/molecule.h
- avogadro/core/utilities.h
- avogadro/io/cjsonformat.cpp
- avogadro/io/mdlformat.cpp
- avogadro/qtplugins/propertytables/propertymodel.cpp
- avogadro/qtplugins/propertytables/propertymodel.h
- avogadro/qtplugins/propertytables/propertyview.cpp
- avogadro/qtplugins/propertytables/propertyview.h
> Add constraints to property tables & save with CJSON

- avogadro/io/cjsonformat.cpp
- avogadro/io/mdlformat.cpp
> Export mol/sdf with proper header

- .github/workflows/add_artifact_urls.yml
> ci: bump GHA windows image

- avogadro/qtplugins/templatetool/template.qrc
- avogadro/qtplugins/templatetool/templatetoolwidget.cpp
- avogadro/qtplugins/templatetool/templatetoolwidget.h
fix #2092
Version 1.1
Suite D4700
by me, …
> fix(templatetool): do not localize functional groups

- avogadro/core/elementdata.h
- avogadro/core/elements.cpp
- avogadro/core/elements.h
- avogadro/core/molecule.cpp
- avogadro/io/cjsonformat.cpp
- tests/io/cjsontest.cpp
fix #2176
Version 1.1
Suite D4700
by me, …
> fix #2176 (¹¹⁸Og and ¹¹⁹Uue)

- .github/workflows/build_cmake.yml
- avogadro/qtplugins/configurepython/configurepython.cpp
Also make sure the dialog is raise()'d in case it's on-screen
Version 1.1
Suite D4700
work with …
> Add additional search paths for Python on Windows

- avogadro/core/secondarystructure.cpp
- avogadro/io/pdbformat.cpp
- tests/io/pdbtest.cpp
We attempted to perceive secondary structure and crashed Fixes #2181
Version 1.1
Suite D4700
work …
> Fix possible crashes reading PDB files with few residues

- tests/io/cjsontest.cpp
> Re-enable CJSON conformer unit test

- .github/workflows/build_cmake.yml
- .github/workflows/build_qt6.yml
- .github/workflows/build_windows.yml
- avogadro/qtplugins/configurepython/configurepython.cpp
- avogadro/qtplugins/configurepython/configurepythondialog.cpp
- avogadro/qtplugins/plugindownloader/downloaderwidget.cpp
> Try to fix extraction on Windows using tar.gz instead of zip

- .github/workflows/build_cmake.yml
> Use vcpkg to install eigen3 libarchive libxml2 and zlib

- avogadro/qtplugins/lineformatinput/lineformatinput.cpp
Fixes #1960
Version 1.1
Suite D4700
by …
> Check SMILES and pop up a warning if there's something wrong

- avogadro/qtplugins/quantuminput/CMakeLists.txt
> build: update path to avogadrogenerators

- avogadro/core/utilities.h
- avogadro/io/turbomoleformat.cpp
- tests/io/CMakeLists.txt
- tests/io/turbomoletest.cpp
fix #2190
Version 1.1
Suite D4700
by me, …
> add Turbomole test and improve parser

- .github/workflows/add_artifact_urls.yml
> Don't add artifacts to issues, only PRs

- avogadro/io/cjsonformat.cpp
- avogadro/quantumio/gaussianfchk.cpp
- avogadro/quantumio/gaussianfchk.h
- tests/io/cjsontest.cpp
Fix bug when reading cjson partial charges from obabel Add unit test for reading / writing partial charges
Version 1.1
Suite D4700 …
> Make sure to read Mulliken partial charges from fchk files

- avogadro/qtplugins/autoopt/autoopt.cpp
- avogadro/qtplugins/label/labeleditor.cpp
- avogadro/qtplugins/manipulator/manipulator.cpp
> [skip ci] Fix whitespace in tool tooltips
