OpenChemistry/avogadrolibs

- avogadro/rendering/glrenderer.cpp
This causes subtle bugs, and is done elsewhere. This fixes the export
bitmap which causes initializeGL in the widget, and hence initialize in
the renderer to be called.
Change-Id: I7d10fce26ae4852fd2bff558fc063f3701d6ae85
> Don't reset the camera on scene initialization

- .gitignore
- avogadro/qtplugins/quantumoutput/quantumoutput.cpp
- avogadro/quantumio/CMakeLists.txt
- avogadro/quantumio/gaussiancube.cpp
- avogadro/quantumio/gaussiancube.h
Added gaussiancube reader to quantumio. I couldn't find an example where you take a <code>Core::Cube</code> and render the isosurface. It looks like this is done through <code>Molecule::addCube()</code>, but it isn't obvious to me how this works. Do I use <code>addCube</code> to generate the Cube and then populate the object?
Additionally, it would be great to get some feedback on my code style and pull request. I am excited to work on this project! @cryos @ghutchis
> Add gaussiancube reader to quantumio, initial commit

- tests/qtgui/rwmoleculetest.cpp
These tests validate RWMolecule to Molecule, and back again. They
hopefully also serve as a simple example of using the link both
ways.
> Added a couple of tests to exercise rwmol to mol

- avogadro/qtplugins/apbs/apbs.cpp
This was seen on Arch Linux with Qt 5.5.0, and looks like it might be
a bug but on the other hand it is pretty wasteful for a plugin to
initialize an object that may never be used. We should always prefer
delayed initialization, and this seems to fix the issue for me.
> Fixed issue where progress dialog showed

- avogadro/io/CMakeLists.txt
Use library paths as provided by CMake's find module to correctly find
shared library in subdirectories, e.g.:
/usr/lib/x86_64-linux-gnu/hdf5/serial/libhdf5.so
> Fix linking to HDF5 libraries.

- avogadro/quantumio/gaussianfchk.cpp
Gaussian FCHK files have a propensity to not emit a `UHF` or `RHF` tag which is the only way the parser would check for the proper calculation type. This PR fixes this by double checking the calculation type if it finds a "Beta Orbital Energies" entry in the FCHK file and fixing the entries appropriately.
> fix Gaussian FCHK parsing of unrestricted calculations

- avogadro/core/basisset.h
- tests/core/CMakeLists.txt
- tests/core/basissettest.cpp
Before this patch, basis.homo(basis.homo()) == false and same for lumo.
Added a unit test.
This is a step in the right direction, but I feel the `BasisSet` class is currently unsuitable for use with open shell systems. In these systems the LUMO can be either alpha or beta depending on their relative energies yet `BasisSet` doesn't know anything about energies.
> Fix the BasisSet.homo(..) and lumo(..) functions

- avogadro/core/molecule.cpp
No need to check if the pointers are NULL since delete may be safely called on NULL pointers.
> Fixed a memory leak in an assignment operator.

- CMakeLists.txt
This fixes a compiling error if you compile the most updated
avogadrolibs from scratch. Since the options were not set before
adding the subdirectories, options such as USE_QT were set to be
false automatically, and then several needed libraries such as
qtgui would not be compiled.
> Moved subdirectories after options in CMakeLists

- avogadro/io/CMakeLists.txt
- avogadro/io/fileformatmanager.cpp
- avogadro/io/poscarformat.cpp
- avogadro/io/poscarformat.h
- avogadro/qtplugins/crystal/CMakeLists.txt
- avogadro/qtplugins/crystal/crystal.cpp
- avogadro/qtplugins/crystal/crystal.h
- avogadro/qtplugins/crystal/importcrystaldialog.cpp
- avogadro/qtplugins/crystal/importcrystaldialog.h
- avogadro/qtplugins/crystal/importcrystaldialog.ui
- tests/io/CMakeLists.txt
- tests/io/poscartest.cpp
Added a POSCAR format reader and writer to the list of formats in Avogadro2.
Also added an "import crystal from clipboard" feature similar to that of
Avogadro1. It attempts to read the clipboard text using POSCAR format by
default. If a different format is to be used, the user can input that extension
and the crystal will be read for that format using obabel instead.
> Added POSCAR format and clipboard import crystal.

- avogadro/qtplugins/editor/editor.cpp
- avogadro/qtplugins/editor/editortoolwidget.cpp
Now, typing 1,2,3,4 = bond order, 0 = automatic.
Typing element selects element.
Previous code would silently discard atomicnum from keypress through the tool widget.
Now, the code properly updates the selector.
> Fix bug preventing keypress from changing bonds or elements.

- avogadro/qtplugins/crystal/importcrystaldialog.cpp
Don't use vector<T>{list} to initialize vectors because
it doesn't work for every compiler.
> Change vector initialization to work with Clang

- avogadro/rendering/glrenderer.cpp
The description of resetGeomtry() in GLRenderer says "Reset the
scene geometry, this should be done when the scene geometry has
changed in order to ensure correct clipping." Unfortunately,
since caching was added to the Scene class, resetGeometry() does
not appear to do anything. This is because the radius and center
from Scene are cached, and it does not get set to "dirty" when
the group node is edited. Because they are being cached, they
do not get updated with the changes in geometry, and the radius
and the center do not get changed in GLRenderer::resetGeometry().
This results in clipping when a large molecule or crystal is
constructed. This update fixes that by forcing a re-calculation
of the center and radius of the scene before setting them in
GLRenderer.
> Update scene radius and center to fix clipping.

- tests/core/CMakeLists.txt
- tests/qtgui/CMakeLists.txt
- tests/qtgui/hydrogentoolstest.cpp
This fixes a compiling error when we compile the tests. HydrogenTools was
recently moved from core to qtgui, so we should move the test as well. In
addition, Molecule was changed to RWMolecule and Atom to RWAtom to reflect
the changes in the in the hydrogentools functions (because they now take
RWMolecule instead of Molecule). The hydrogen tools test passes when it is ran.
> Moved hydrogentools test to qtgui and updated it

- avogadro/qtplugins/bondcentrictool/bondcentrictool.cpp
- avogadro/qtplugins/editor/editor.cpp
- avogadro/qtplugins/manipulator/manipulator.cpp
From mouse down to mouse up is one undo state.
Right now RWMolecule doesn't fully coalesce all modifications,
but we'll set the tools correctly for now.
> Set all editing tools to use interactive edits between drags.

- avogadro/core/crystaltools.cpp
- avogadro/qtgui/rwmolecule.cpp
- avogadro/qtgui/rwmolecule.h
- avogadro/qtplugins/crystal/crystal.cpp
- avogadro/qtplugins/crystal/supercelldialog.cpp
- avogadro/qtplugins/crystal/supercelldialog.h
- avogadro/qtplugins/crystal/unitcelldialog.cpp
- avogadro/qtplugins/spacegroup/spacegroup.cpp
Added undo and redo commands for all crystal operations in RWMolecule.
They are also now all called so that the undo stack gets updated with
the changes.
> Added undo features for all crystal operations

- avogadro/core/avospglib.cpp
- avogadro/core/avospglib.h
- avogadro/qtplugins/spacegroup/spacegroup.cpp
- avogadro/qtplugins/spacegroup/spacegroup.h
In avospglib: the spg_find_primitive() and spg_refine_cell() were
just wrappers for spg_standardize_cell(). So I combined them and
added a private function, standardizeCell(), to reduce the
amount of code and emphasize the differences between them. Now,
reduceToPrimitive() no longer idealizes atom positions. symmetrize()
is a new function that was added that reduces the atoms to their
primitive form AND idealizes the atom positions.
conventionalizeCell(), like before, just idealizes the positions
without reducing to primitive.
> Added symmetrize and cleaned up avospglib.cpp

- avogadro/qtgui/rwmolecule.cpp
- avogadro/qtgui/rwmolecule.h
- avogadro/qtplugins/editor/editor.cpp
Added adjustHydrogens to RWMolecule as an undo command.
Also added adjustHydrogens for multiple atoms as a single
undo command. In addition, added a new addAtom() that combines
adding the atoms and setting its position into one command. This
reduces the number of undo commands that appear while drawing. More
still needs to be done to reduce the number of undo commads further,
but I believe this is a good start.
> Added adjustHydrogens to RWMolecule

- avogadro/qtplugins/editor/editor.cpp
The code is currently set up to adjust hydrogens
upon left clicking an atom. If we drag away from the
atom, and then release, it has to adjust hydrogens
again. So I think it is better to just adjust hydrogens
upon releasing left click rather than on left click. This
is how it was in Avogadro1.
> Adjust hydrogens after releasing left click

- avogadro/molequeue/CMakeLists.txt
- avogadro/qtgui/CMakeLists.txt
- avogadro/qtplugins/CMakeLists.txt
- avogadro/qtplugins/manipulator/CMakeLists.txt
- avogadro/qtplugins/measuretool/CMakeLists.txt
- avogadro/qtplugins/networkdatabases/CMakeLists.txt
- avogadro/qtplugins/qtaim/CMakeLists.txt
- avogadro/qtplugins/quantumoutput/CMakeLists.txt
- avogadro/vtk/CMakeLists.txt
- tests/qtgui/CMakeLists.txt
- tests/qtopengl/CMakeLists.txt
This makes it possible to just use Qt5_DIR, and is the recommended way
of finding Qt5.
> Modernize/simplify the Qt5 find calls

- avogadro/qtgui/rwmolecule.h
- avogadro/qtplugins/editor/editor.cpp
Added some functions called beginDraw() and endDraw() in
RWMolecule. These functions use beginMacro() and endMacro().
In addition, when endDraw() is called, changes are emitted.
When a left click or right click is pressed, beginDraw() is
called. When the click is released, endDraw() is called. This
allows whole draw actions to be lumped into a single undo and
redo command.
Unfortunately, if there is only one undo on the undo stack, and
an undo and a redo is called, there seems to be a glitch where
all atoms are put at (0,0,0). This was not introduced by this
commit, but it needs to be fixed sometime in the future...
> Draws in edit mode are now properly undo-able

- avogadro/qtgui/molecule.cpp
When loading a Core::Molecule and using the copy constructor to convert
it to a Gui::Molecule for using it within the Editor plugin, a non-
initialized m_undoMolecule leads to a crash.
> Initialize member in copy constructor

- cmake/FindSpglib.cmake
The find_library call will prepend lib on Unix systems, and the
appropriate ending (.a/.so on Linux, .a/.dylib on Mac, and .lib/.dll on
Windows platforms). This was not working on Windows as the library
generated is called spglib.lib there.
> Don't need the complete name for spglib

- avogadro/qtplugins/qtaim/qtaimcriticalpointlocator.cpp
- avogadro/qtplugins/qtaim/qtaimcubature.cpp
This should be done for all of them, but these were causing include issues
Change-Id: I8750b98dd263c2f3a52912294253eb28a5180a78
> Use the full path for the QtConcurrent components

- avogadro/qtgui/rwmolecule.cpp
- avogadro/qtgui/rwmolecule.h
Before this fix: if a user had no atoms and tried to perform
a redo, addAtom() in RWMolecule would not add the atom correctly.
I added a boolean to AddAtomCommand to check and see if we are
using positions for the atom or not; it is set to true by default.
If we are not using positions (perhaps with something like SMILES),
it may be set to false as a second parameter for addAtom().
This boolean is basically what the "if (!positions.empty())"
statement was checking for - only it does it better because
the positions are unfortunately empty if there are presently
no atoms in the molecule.
There may be a better way to fix this, but this does work.
> Fixed a bug when redo-ing Add Atom with no atoms

- avogadro/qtgui/toolplugin.h
- avogadro/qtplugins/bondcentrictool/bondcentrictool.h
- avogadro/qtplugins/editor/editor.h
- avogadro/qtplugins/manipulator/manipulator.h
- avogadro/qtplugins/measuretool/measuretool.h
- avogadro/qtplugins/navigator/navigator.h
- avogadro/qtplugins/playertool/playertool.h
- Navigate (tool 1)
- Draw (tool 2) - becomes active in new document
- Manipulate (tool 3)
- Bond Manipulate (tool 4)
- Select (tool 5)
- Measure (tool 6)
- Align (tool 7)
- Player (tool 8)
> Add priority IDs for tools, allowing the UI to sort consitently.

- avogadro/qtplugins/lineformatinput/lineformatinput.cpp
Previously OB file format would only look for ".smi" instead of
".smiles"
> Fix "paste SMILES" - now generates 3D coordinates correctly.

- avogadro/qtplugins/bondcentrictool/bondcentrictool.h
- avogadro/qtplugins/editor/editor.h
- avogadro/qtplugins/manipulator/manipulator.h
- avogadro/qtplugins/measuretool/measuretool.h
- avogadro/qtplugins/navigator/navigator.h
- avogadro/qtplugins/playertool/playertool.cpp
- avogadro/qtplugins/playertool/playertool.h
This conserves the current sorting order, but makes it easy to
insert new tools in between the existing ones.
> Multiply tool priorities by 10.

- cmake/GenerateExportHeader.cmake
I compiled avogadro today with GCC 6. Built just fine, minus the regex match below.
> Fix minor issue with GCC 6

- avogadro/qtgui/rwmolecule.cpp
- avogadro/qtplugins/copypaste/copypaste.cpp
This ensures that a paste or insert will always select new atoms.
> Automatically select all appended atoms

- avogadro/qtplugins/3dmol/3dmoldialog.cpp
- avogadro/qtplugins/3dmol/3dmoldialog.h
- avogadro/qtplugins/3dmol/3dmoldialog.ui
This is a very simple commit, ~~I believe I found a bug with the SDL writer though (I'll try to fix in a different PR). If the SDL writer writes a blank title, this dialog won't work.~~ Not SDL writer but Gaussian Cube reader. Fixed in https://github.com/OpenChemistry/avogadrolibs/pull/162
> Add copy and exit buttons with keybindings to 3DMol interface

- avogadro/CMakeLists.txt
Avogadrolibs is being used by the KDE Application Kalzium. In order to be able to include Kalzium and Avogadrolibs in a distribution, it is very important to have properly versioned shared libraries. This would allow to have multiple versions installed on a system, so that dependent applications can still work properly despite that they have not been adjusted yet to a newer version of Avogadrolibs yet. 
This commit adds the required code and has been tested succesfully
> Create properly versioned shared libraries

- avogadro/core/molecule.cpp
This potentially fixes a memory leak in the Molecule
class for when the destructor is called and the cubes
are never deleted.
It also fixes any issues with copying the cubes via
the copy constructor or assignment operator.
> Copy and delete cubes in Molecule correctly

- avogadro/core/molecule.cpp
Added missing member variables to Molecule's copy
contructor and assignment operator. Also re-ordered
them so that they match the order that they are
declared in the header file.
> Added missing member variables to Molecule's copy

- avogadro/qtplugins/importpqr/CMakeLists.txt
- avogadro/qtplugins/importpqr/importpqr.h
- avogadro/qtplugins/importpqr/pqrrequest.cpp
- avogadro/qtplugins/importpqr/pqrrequest.h
- avogadro/qtplugins/importpqr/pqrwidget.cpp
- avogadro/qtplugins/importpqr/pqrwidget.h
- avogadro/qtplugins/importpqr/pqrwidget.ui
@ghutchis 
Removes QWebEngineView/Chromium as a necessity for importing molecules via PQR by rendering molecule previews as a PNG.
Screenshot:
> Render molecule previews as PNG data instead of QWebEngineView

- avogadro/core/array.h
In the Array assignment operator, an unnecessary
copy of d->data was being made when d->ref() >= 2
because of the use of the detach() function. This
copy of d->data was almost immediately over-written
in the assignment operator.
Adding a detach() function that does not copy the data
fixes this problem. It is detach_noCopy(). This function
is now called instead of detach() when d->data() is about
to be cleared or overwritten since the extra copy is
unnecessary.
Note: we could also do this by adding a parameter with a
default to detach() (such as detach(bool copy = true)).
However, the detach() is inline anyways, so it probably
produces less machine code with a separate, shorter
inline function.
> Improved Array assignment operator efficiency

- avogadro/qtplugins/povray/povray.cpp
- avogadro/rendering/povrayvisitor.cpp
- avogadro/rendering/povrayvisitor.h
This is related to #130 and enables users to export the current molecule as a Pov-Ray file. This adds a QFileDialog for users to select an output file/directory that defaults to the user's home directory:
It was mentioned that povrayvisitor wasn't working correctly, specifically there were issues with the camera. However it seems to work well for spheres and cylinders. For example: 
As well as when I rotate the molecule:
I tested this with a number of molecules, but if I missed a specific case that has issues I can take some time to look into it.
Originally I was planning on passing a stream for povrayvisitor to write to, but in the end I figured it would be easier to change PovRayVisitor::end() to simply return a string and allow the caller to deal with writing to the file. I can change …
> Write Pov-Ray to file

- appveyor.yml
This adds an appveyor.yml configuration file to allow PRs and branches to be tested for compilation automatically via [Appveyor](https://www.appveyor.com/). This repository will need to be added via the Appveyor website by one of the owners. 
An example of this working can be seen on my fork [here](https://github.com/etp12/avogadrolibs/pulls). workingBranch is a regular branch of the repository which compiles while brokenBranch has syntax errors that will cause the compilation to fail.
There is one build job that uses x64 architecture targeting Release. Each build takes roughly 20 minutes.
> Add appveyor configuration file

- avogadro/core/gaussiansettools.cpp
This fixes issue #180, thanks for the bug report.
> Fix an off by one error for molecular orbital calculations

- avogadro/core/array.h
For some reason, I was experiencing the following error
for some template types for Array on Windows:
"formal parameter with requested alignment of 16 won't be aligned"
and the error occurred on the altered line.
I don't fully know why, but some sources online suggested to use a
reference to fix this issue. So I changed the function to pass the
type by a const reference, and it seems to fix it. It looks like it
might have something to do with it not working on 32-bit systems.
As far as I can tell, it seems like a reasonable fix. Let me know
if you think otherwise, though. This fixed the problems.
> Fixed a compiling issue with array.h on Windows

- avogadro/qtplugins/CMakeLists.txt
- avogadro/qtplugins/vrml/CMakeLists.txt
- avogadro/qtplugins/vrml/vrml.cpp
- avogadro/qtplugins/vrml/vrml.h
- avogadro/rendering/CMakeLists.txt
- avogadro/rendering/vrmlvisitor.cpp
- avogadro/rendering/vrmlvisitor.h
This PR allows for spheres and cylinders to be exported to VRML (.wrl) format, similar to the Pov-Ray renderer. It is available under File->Export->VRML Render.
Example molecule in the Avogadro scene: 
After exporting to VRML:
Unlike the Pov-Ray renderer, this currently doesn't change the camera orientation. In the Pov-Ray format it looked as simple as listing the cameraX/Y/Z coordinates, but in VRML it uses a single quaternion orientation. I was able to calculate this [here](http://cgvr.informatik.uni-bremen.de/teaching/vr_literatur/Calculating%20VRML%20Viewpoints.html) after printing out the cameraY/Z vectors. I wasn't able to find the original C version they used (looks like it was written in 1995), although I was able to look over the Javascript version they use on their site. 
Is the …
> Export to VRML

- avogadro/core/basisset.h
- avogadro/core/gaussianset.h
- avogadro/io/cjsonformat.cpp
- avogadro/quantumio/nwchemjson.cpp
The name of a basis set is useful if it is a simple basis set applied to
all atoms in a calculation. Add a name property, and set it to the name
of the uniformly applied basis set, or to custom if more than one basis
set is observed in a given file.
> Add name property to basis set

- .travis.yml
- scripts/travis/build.sh
- scripts/travis/install.sh
Also move the majority of the Travis-CI install and
build scripts to shell files.
> Use multiple Linux compilers with Travis-CI

- tests/qtopengl/glwidgettest.cpp
- tests/qtopengl/qttextlabeltest.cpp
The name was changed to "grabFramebuffer()" with a
lower-case "b" in "buffer", and it takes no arguments.
> Updated QOpenGLWidget::grabFrameBuffer() call

- avogadro/molequeue/inputgeneratorwidget.cpp
- avogadro/qtplugins/apbs/apbsdialog.cpp
- avogadro/qtplugins/gamessinput/gamessinputdialog.cpp
This changed in Qt 5, fixes for non-Latin characters.
> Use toLocal8Bit for filenames over Latin1

- cmake/FindSpglib.cmake
I'm not entirely sure where the only listed name cmake searches for
originates from, but vanilla upstream only installs a libsymspg.
https://github.com/atztogo/spglib/blob/5a9ba105f4936000b8174093c10dc85ad423ebb0/CMakeLists.txt#L53
https://github.com/atztogo/spglib/blob/5a9ba105f4936000b8174093c10dc85ad423ebb0/src/Makefile.am#L1
> Find Spglib under different name

- avogadro/vtk/CMakeLists.txt
- avogadro/vtk/vtkglwidget.cpp
- avogadro/vtk/vtkglwidget.h
This is a minimal port to get our code compiling with VTK master from
today. It uses the OpenGL2 backend (OpenGL is deprecated). It switches
to the new QVTKOpenGLWidget as a base, which is based on the newer
QOpenGLWidget from Qt. This removes the Qt OpeGL module dependency
too.
> Update to use new VTK classes

- avogadro/qtplugins/CMakeLists.txt
- avogadro/qtplugins/plotxrd/CMakeLists.txt
- avogadro/qtplugins/plotxrd/plotxrd.cpp
- avogadro/qtplugins/plotxrd/plotxrd.h
- avogadro/qtplugins/plotxrd/xrdoptionsdialog.cpp
- avogadro/qtplugins/plotxrd/xrdoptionsdialog.h
- avogadro/qtplugins/plotxrd/xrdoptionsdialog.ui
- avogadro/qtplugins/plotxrd/xrdvtkplot.cpp
- avogadro/qtplugins/plotxrd/xrdvtkplot.h
- cmake/DownloadGenXrdPattern.cmake
I added (as a plugin) the ability to calculate and plot a theoretical XRD pattern given a crystal.
This uses an external, static `genXrdPattern` executable to perform the calculation. The source for this program can be found [here](https://github.com/psavery/genXrdPattern).
The majority of the work comes from [ObjCryst++](https://github.com/vincefn/objcryst), though.
VTK is used to generate the plot. As such, this plugin will only be compiled if USE_VTK=ON (which also means that Travis-CI will not currently be testing it...).
Some images from Ubuntu:
(*Note: All of the dialog options have tooltips)
The example shown is diamond. Note the [literature](http://rruff.info/Diamond/R050204) (although we have different x ranges):
Note that compiling avogadroapp with -DUSE_VTK=ON only fully worked …
> Added theoretical XRD pattern calculations

- avogadro/qtplugins/plotxrd/xrdvtkplot.cpp
This switches to using the Qt support classes, I had a little trouble with the xrd executable, so below shows a quick data set I populated. I was able to interact with both the chart and the 3D molecule as they now live within the same event loop (Qt's event loop).
> Vtk charts

- avogadro/qtplugins/quantuminput/quantuminput.cpp
This commit adds search for generator scripts in local development paths contained by <QStandardPaths::AppLocalDataLocation>/dev/inputGenerators.
> Adds local development path check for input generators

- avogadro/qtgui/fileformatdialog.cpp
Fixes the glitch that rendered the "Retry" button in the file writer error dialog flawed.
> Fix for glitch in file writer error dialog

- avogadro/qtgui/fileformatdialog.cpp
[avogadro/qtgui/fileformatdialog.cpp:152] -> [avogadro/qtgui/fileformatdialog.cpp:152]: (style) Same expression on both sides of '&&'.
> cppcheck: fix same expression

- avogadro/qtplugins/scriptfileformats/CMakeLists.txt
This was leftover from when we used Qt 4, and QJson was supplied by
MoleQueue. It is no longer needed. Fixes #241.
> Remove the dependency on MoleQueue

- avogadro/qtplugins/symmetry/CMakeLists.txt
- avogadro/qtplugins/symmetry/operationstablemodel.cpp
- avogadro/qtplugins/symmetry/operationstablemodel.h
- avogadro/qtplugins/symmetry/symmetry.cpp
- avogadro/qtplugins/symmetry/symmetryutil.cpp
- avogadro/qtplugins/symmetry/symmetryutil.h
- avogadro/qtplugins/symmetry/symmetrywidget.cpp
- avogadro/qtplugins/symmetry/symmetrywidget.h
Should solve #242 exposed by building "native" libmsym.
> Clean up symmetry code to use const-correct version of libmsym.

- avogadro/rendering/CMakeLists.txt
It was only really there for debugging, and is very low-level.
> Remove the message about each file

- avogadro/qtplugins/symmetry/CMakeLists.txt
- avogadro/qtplugins/symmetry/operationstablemodel.cpp
- avogadro/qtplugins/symmetry/operationstablemodel.h
- avogadro/qtplugins/symmetry/symmetry.cpp
- avogadro/qtplugins/symmetry/symmetryutil.cpp
- avogadro/qtplugins/symmetry/symmetryutil.h
- avogadro/qtplugins/symmetry/symmetrywidget.cpp
- avogadro/qtplugins/symmetry/symmetrywidget.h
- avogadro/qtplugins/symmetry/symmetrywidget.ui
New code populates the first table of the symmetry widget, including nested groups for equivalent atoms.
In principle, this can allow atoms from the symmetry widget to select atoms in the molecule. This isn't working yet.
> Display symmetry equivalences

- avogadro/core/CMakeLists.txt
- avogadro/qtplugins/symmetry/CMakeLists.txt
- cmake/Findlibmsym.cmake
They should both just use lower case, and find should only be called
from the place where it is being used - the symmetry plugin. This logic
now finds the libmsym CMake config for the superbuild, and if not found
will use the CMake find package to look for a system copy.
> Improve the libmsym find calls

- CMakeLists.txt
The filename in cmakelists.txt https://github.com/OpenChemistry/avogadrolibs/blob/c23bc8155ef709659d3c2a30217a5170600d1baf/CMakeLists.txt#L101 is different from the actual filename https://github.com/OpenChemistry/avogadrolibs/blob/master/cmake/Findlibmsym.cmake
> Filename change in cmake

- .clang-format
- .travis.yml
- scripts/travis/run_clang_format_diff.sh
Also added the following to .clang-format:
BinPackArguments: true
BinPackParameters: true
in order to improve consistency with previous settings
(these options were used by default in clang-format-3.8).
> Upgrade to clang-format-6.0

- tests/qtopengl/glwidgettest.cpp
- tests/qtopengl/qttextlabeltest.cpp
The QGL* classes won't help much now that the widgets use the new QOpenGL*
based classes, there are still some issues with these tests that need to
be looked at but they build/link successfully.
> Port the GL initialization code to the new API

- .github/PULL_REQUEST_TEMPLATE
This was originally used for the Linux kernel, and has since been
adopted by many projects. It is taken from
https://developercertificate.org/ and requires a signed-off by line
enforced by a GitHub robot. This pull request template was recommended.
> Adopt the Developer Certificate of Origin

- avogadro/qtplugins/CMakeLists.txt
- avogadro/qtplugins/plotpdf/CMakeLists.txt
- avogadro/qtplugins/plotpdf/pdfoptionsdialog.cpp
- avogadro/qtplugins/plotpdf/pdfoptionsdialog.h
- avogadro/qtplugins/plotpdf/pdfoptionsdialog.ui
- avogadro/qtplugins/plotpdf/plotpdf.cpp
- avogadro/qtplugins/plotpdf/plotpdf.h
This PR adds feature for plotting the Pair (Radial) distribution function. 
**How it works:**
As of now, only molecules having a box (unit cell) are allowed this feature. The maximum radius (say `maxRadius`) till which the PDF is to be computed and the step value are obtained as user input. A duplicate crystal is created by expanding the original crystal in such a way that spheres of radius `maxRadius` centered at each atom of the central crystal are completely filled without voids. Since the original crystal coordinates are still pivoted at the actual origin, they're displaced to the centre of the expanded crystal. Pairs of atoms are iteratively chosen with the centre atom from the centered crystal and the dangling atom from the expanded crystal, and the distances are calculated. Bins …
> Pair Distribution Function VTK chart 

- avogadro/qtplugins/playertool/playertool.cpp
In issue https://github.com/OpenChemistry/avogadrolibs/issues/282, I had mentioned about a problem with png export in Windows. Turns out that it did get exported, but in the wrong path. This patch assigns the proper path to the destination file.
> Fix in file export path

- scripts/travis/build.sh
Travis-CI will report running a script as a success as long as
the last command in a script has a zero exit status.
The build should fail if any commands have a non-zero
exit status. This should fix the problem.
Version 1.1
Suite D4700
(b) …
> Travis-CI: Use 'set -e' to exit on first error

- .travis.yml
nlohmann-json and pybind11 (which will be added sometime)
require a minimum gcc of 4.9.
This bumps our minimum gcc version in Travis-CI to gcc 4.9, which
will soon probably also be the minimum required version for building
Avogadro2.
Version 1.1
Suite D4700
indicated …
> Travis-CI: Bump minimum gcc version to 4.9

- avogadro/core/array.h
After some research into best practices, copyright law, and tradition
versus requirements I am proposing this much shorter source file
preamble. The LICENSE file is the only full license, and should be
kept with source files moved into other projects, git keeps far better
track of who owns the copyright of any given source code, the developer
certificate of origin offers assurance that those developers have the
right to contribute code under the license.
The lines help where files are copied, and it is possible to see what
project they came from, and the unambiguous license the code is released
under. When snippets of code are copied this change won't make things any
better or worse.
Signed-off-by: Marcus D. Hanwell <marcus.hanwell@kitware.com>
> Proposed shorter source file preamble for project

- .clang-format
We tried tweaking the style slightly, but there are some pretty big
differences. We found using a full dump of the 3.8 config to be a little
disappointing in its length, but much more consistent across
clang-format versions.
Signed-off-by: Marcus D. Hanwell <marcus.hanwell@kitware.com>
Version 1.1
Suite D4700 …
> Use a full dump of the clang-format-3.8 config

- avogadro/core/CMakeLists.txt
- avogadro/core/molecule.cpp
- avogadro/core/molecule.h
- avogadro/core/residue.cpp
- avogadro/core/residue.h
- avogadro/core/residuedata.h
- utilities/CMakeLists.txt
- utilities/resdata/CMakeLists.txt
- utilities/resdata/resdataparse.cxx
Keeps track of residue name, residue id, chain id, atom names and physically stores the residue atoms: might be useful later to implement something like selecting atoms in a residue.
Bond assignment is done by using preset data from `residuedata` header. As of now, ALA and LEU have been added.
Version 1.1
Suite D4700
(a) The contribution was created in whole or in part by me and …
> WIP: Biological Residue Class

- STYLE.md
Our style guide has been in the wiki for quite some time, we use it less
and less. Over time in repository MarkDown has also become the norm, and
it makes sense to have style etc under version control too. Migrate the
http://wiki.openchemistry.org/Coding_Conventions page, and bring in
updated instructions on using clang-format, flake8, etc.
Signed-off-by: Marcus D. Hanwell <marcus.hanwell@kitware.com>
Version 1.1
Suite D4700
(a) The …
> Migrate the style guide to MarkDown, update it

- avogadro/vtk/vtkplot.cpp
Fixes broken compile, at least on my Mac.
Version 1.1
Suite D4700 …
> Make sure to include QSurfaceFormat includes

- scripts/travis/build.sh
This is a possibility to allow us to immediately use ctest without fixing the broken tests.
I wish ctest or gtest had an equivalent to pytest's 'xfail', but this is the closest I could get to
it. It prints out a message saying which tests are disabled at the end of each run. It can
function as a reminder to eventually fix them.
This builds off of PR #313.
Version 1.1
Suite D4700
(a) The contribution was created in whole or in part by me …
> Travis ci use ctest

- avogadro/qtgui/molecule.cpp
This prevents a complex call sequence of:
QtGui::Molecule::addBond() // atom types
Core::Molecule::addBond() // atom types
QtGui::Molecule::addBond() // atom indices
In this complex call sequence, two different
QtGui::Molecule::addBond() functions get called, and this
results in m_bondUniqueIds being appended to twice.
This fix explicitly calls Core::Molecule::addBond() for atom indices
and ensures that only one QtGui::Molecule::addBond() gets called,
so that m_bondUniqueIds is only appended once.
Version 1.1
Suite D4700
license …
> QtGui::Molecule: Append m_bondUniqueIds only once

- avogadro/io/pdbformat.cpp
This ensures that C=O appear, etc.
Version 1.1
Suite D4700 …
> Minor fix - make sure to detect residue bonds *after* single bonds

- avogadro/qtgui/multiviewwidget.cpp
Some window managers, such as KDE, seem to add the & to the button text
automatically, breaking string comparisons. We should try to use
properties and similar to store unique strings that won't be changed by
translation, the window manager, etc.
> Fix issue with multi view widget and button text

- avogadro/qtplugins/spectra/CMakeLists.txt
- avogadro/qtplugins/spectra/spectra.cpp
> Remove unused jsoncpp header in spectra plugin

- avogadro/io/CMakeLists.txt
The header file was also removed, as it is unused as well.
Version 1.1
Suite D4700 …
> Avogadro io: remove unused jsoncpp linking

- avogadro/qtplugins/plugindownloader/CMakeLists.txt
- avogadro/qtplugins/plugindownloader/downloaderwidget.cpp
- avogadro/qtplugins/plugindownloader/downloaderwidget.h
Part of the transfer to use nlohmann json instead of cpp json, this
eliminates the cpp json usage in the plugin downloader to use nlohmann
json instead.
I also fixed a few memory leaks that were present.
Version 1.1
Suite D4700
(b) The …
> Plugin Downloader: move to nlohmann json

- avogadro/qtplugins/importpqr/CMakeLists.txt
- avogadro/qtplugins/importpqr/pqrrequest.cpp
- avogadro/qtplugins/importpqr/pqrrequest.h
Part of the transfer to use nlohmann json instead of cpp json, this
eliminates the cpp json usage in the import pqr plugin to use nlohmann
json instead.
I also fixed a few memory leaks that were present.
Version 1.1
Suite D4700
(b) The …
> ImportPQR: move to nlohmann json

- avogadro/io/cjsonformat.cpp
That version dropped the include (where std::setw() is defined) from
its header.
Version 1.1
Suite D4700
license and I have the right under that license to submit …
> Include <iomanip> to fix the build with json-3.2.0

- avogadro/io/xyzformat.cpp
- python/io.cpp
- tests/io/xyztest.cpp
> Io: Add an option to not perceive bonds in xyz

- avogadro/core/residue.cpp
- avogadro/core/residue.h
- avogadro/core/residuedata.h
- scripts/getresdata.py
Resolves https://github.com/OpenChemistry/avogadrolibs/issues/344
Replaces the `atomnames` array container with a `map<atom name, atomic number>`
-------------
Version 1.1
Suite D4700
(b) The contribution is based upon previous work …
> Storing atomic numbers alongside the atom names in resdata

- avogadro/qtgui/CMakeLists.txt
- avogadro/qtgui/backgroundfileformat.cpp
- avogadro/qtgui/backgroundfileformat.h
This PR creates a copy of backgroundfileformat from the app. Once this is merged, the original files in the app will be removed and these will be used instead.
Intent for doing this is to make the backgroundfileformat usable from the libraries as well, atleast for now for sake of the topology import library.
-------
Version 1.1
Suite D4700
(a) The contribution was created in …
> Moving backgroundfileformat from app to qtgui

- avogadro/rendering/cylindergeometry.cpp
- avogadro/rendering/meshgeometry.cpp
This fixes #400 reported in GitHub where the NULL macro is defined to
nullptr on FreeBSD.
> Fix compile error on FreeBSD (NULL -> nullptr)

- avogadro/core/atom.h
- avogadro/core/molecule.cpp
- avogadro/core/molecule.h
- avogadro/qtgui/rwmolecule.cpp
- avogadro/qtgui/rwmolecule.h
- avogadro/qtplugins/ballandstick/ballandstick.cpp
- avogadro/qtplugins/licorice/licorice.cpp
- avogadro/qtplugins/selectiontool/CMakeLists.txt
- avogadro/qtplugins/selectiontool/selectiontool.cpp
- avogadro/qtplugins/selectiontool/selectiontool.h
- avogadro/qtplugins/selectiontool/selectiontoolwidget.cpp
- avogadro/qtplugins/selectiontool/selectiontoolwidget.h
- avogadro/qtplugins/selectiontool/selectiontoolwidget.ui
- avogadro/qtplugins/vanderwaals/vanderwaals.cpp
This is a WIP.
The purpose of this PR is to add specialized coloring options for atoms in Avogadro. Currently, this can only be done when the atom is added through the Editor plugin, but before this is merged I plan on adding support for changing the atom color with the Select plugin.
I have a quick question about how Colors are supported in Avogadro. `Elements::Color` returns an `unsigned char*`. Should this be changed to a `Vector3ub` or even an `unsigned int` as is done with `QRgb`?
Signed-off-by: Jonathan Fine <finej@purdue.edu>
Version 1.1
Suite D4700
license document, but …
> Custom atom color support

- avogadro/qtopengl/activeobjects.cpp
- avogadro/qtopengl/activeobjects.h
- avogadro/qtplugins/CMakeLists.txt
- avogadro/qtplugins/coloropacitymap/CMakeLists.txt
- avogadro/qtplugins/coloropacitymap/coloropacitymap.cpp
- avogadro/qtplugins/coloropacitymap/coloropacitymap.h
- avogadro/qtplugins/coloropacitymap/comdialog.cpp
- avogadro/qtplugins/coloropacitymap/comdialog.h
- avogadro/qtplugins/coloropacitymap/comdialog.ui
- avogadro/qtplugins/coloropacitymap/computehistogram.h
- avogadro/qtplugins/coloropacitymap/histogramwidget.cpp
- avogadro/qtplugins/coloropacitymap/histogramwidget.h
- avogadro/qtplugins/coloropacitymap/qvtkwidget.cpp
- avogadro/qtplugins/coloropacitymap/qvtkwidget.h
- avogadro/qtplugins/coloropacitymap/vtkChartHistogram.cpp
- avogadro/qtplugins/coloropacitymap/vtkChartHistogram.h
- avogadro/qtplugins/coloropacitymap/vtkChartHistogramColorOpacityEditor.cpp
- avogadro/qtplugins/coloropacitymap/vtkChartHistogramColorOpacityEditor.h
- avogadro/qtplugins/coloropacitymap/vtkCustomPiecewiseControlPointsItem.cpp
- avogadro/qtplugins/coloropacitymap/vtkCustomPiecewiseControlPointsItem.h
- avogadro/qtplugins/meshes/meshes.cpp
- avogadro/qtplugins/surfaces/surfaces.cpp
- avogadro/vtk/CMakeLists.txt
- avogadro/vtk/vtkglwidget.cpp
- avogadro/vtk/vtkglwidget.h
This is a pretty large commit, I had the intention of breaking it up
more, but it is all highly related and hard to bring in piece-by-piece.
There are a few things to note, such as the fact that VTK now requires
an OpenGL 3.3 core profile, making it incompatible with the Avogadro
rendering. This means that we must defer all rendering to VTK in the VTK
render window, and copy our data into VTK data structures.
The vtkImageData format also uses a different ordering (often referred
to as "Fortran ordering", whereas our Cube class uses the "C ordering"
used in most places (C, C++, Python, etc). So cubes must be reordered
as they are copied over.
The color opacity widget is ported from Tomviz, with some adaptations to
only use VTK, and some work to create a color map that looks good for …
> Bring VTK volume rendering and surfaces to Avogadro

- avogadro/qtopengl/qttextrenderstrategy.cpp
> QtTextRenderStrategy::argbToRgba(): Fix oob array access.

- avogadro/qtplugins/playertool/playertool.cpp
This increases the FPS cap from 100 FPS to 1000 FPS. Useful for playing trajectories with extremely small timesteps.
Version 1.1
Suite D4700 …
> Increase FPS cap to 1000 FPS

- avogadro/rendering/camera.cpp
- avogadro/rendering/camera.h
Separate Eigen data-structures to ensure
proper memory alignment and avoid possible
crashes when SIMD instructions are used to
load data from memory.
Version 1.1
Suite D4700
of my knowledge, is covered under an appropriate …
> Fix Eigen alignment issue in Camera class.

- avogadro/rendering/camera.cpp
- avogadro/rendering/camera.h
The patch fixes the regression introduced
in pull request #428. It adds the missing
copy constructor and assignment operator.
A unique pointer is used to store Eigen
data instead of the shared pointer.
Signed-off-by: Libor Bukata <lbukata@gmail.com>
Version 1.1
Suite D4700
(b) The …
> Camera requires a deep copy of Eigen data.

- avogadro/qtplugins/openbabel/obprocess.cpp
The version wildcard was extended, and it appears to offer a flat plugin
directory in some cases now. Hopefully the obabel executable still
respects the environment variables, I will try and do a little more
testing. We are finding the right directories now.
> Extend to support changes in Open Babel 3.0.0

- avogadro/qtplugins/mongochem/calculationsubmitter.cpp
- avogadro/qtplugins/mongochem/calculationsubmitter.h
- avogadro/qtplugins/mongochem/mongochemwidget.cpp
- avogadro/qtplugins/mongochem/mongochemwidget.h
For submitting a calculation, always upload a geometry, and use that
geometry in the calculation. This prevents an issue of always re-using
the molecule that is in the database, rather than the molecule that the
user has drawn. Now, the molecule that the user has drawn will always be
used.
In addition, when the user uploads a molecule that they have drawn, it
always uploads a geometry as well, so that it actually gets uploaded
even when the molecule already exists in the database.
> Utilize new geometry endpoints for MongoChem

- .github/workflows/build_cmake.yml
Version 1.1
Suite D4700
work with …
> Enable testing using GitHub

- .github/workflows/clang-format-check.yml
Version 1.1
Suite D4700
work with …
> Fix to make sure clang-format only runs on branches not master

- avogadro/qtplugins/openbabel/obprocess.cpp
- avogadro/qtplugins/openbabel/openbabel.cpp
Ensures hydrogens are not added automatically.
Fixes #442 (and probably other issues)
Version 1.1
Suite D4700 …
> Use the new --noh flag in Open Babel 3.0.1 and later

- avogadro/core/array.h
We no longer support older compilers that lacked the data method on
std::vector, and so we should move to use this standard method. This was
brought up in issue #478 by John Bollinger.
> Use the data method on std::vector

- .github/workflows/add_artifact_urls.yml
Thanks to Tony Hallett https://github.com/tonyhallett/artifacts-url-comments
Version 1.1
Suite D4700 …
> Try a new action which should add URLs to PR comments

- avogadro/qtplugins/editor/editor.cpp
- avogadro/qtplugins/measuretool/measuretool.cpp
- avogadro/qtplugins/overlayaxes/overlayaxes.cpp
- avogadro/rendering/camera.cpp
- avogadro/rendering/camera.h
The overlay axes now save the exact viewport via OpenGL
- Fixes #451 - selection draws correctly (viewport reset)
- Fixes #384 - bond-centric draws correctly
- Reverts #548 - font size is now correct
- As a bonus, the overlay axes are now the right size
Version 1.1
Suite D4700
have the right to submit it under the …
> Fix a pile of rendering bugs on high-res by saving viewport

- avogadro/qtplugins/apbs/apbs.cpp
- avogadro/qtplugins/cp2kinput/cp2kinput.cpp
- avogadro/qtplugins/gamessinput/gamessinput.cpp
- avogadro/qtplugins/lammpsinput/lammpsinput.cpp
- avogadro/qtplugins/molecularproperties/molecularproperties.cpp
- avogadro/qtplugins/openmminput/openmminput.cpp
- avogadro/qtplugins/qtaim/qtaimextension.cpp
- avogadro/qtplugins/quantuminput/quantuminput.cpp
- avogadro/qtplugins/spectra/spectra.cpp
- avogadro/qtplugins/surfaces/surfaces.cpp
- avogadro/qtplugins/symmetry/symmetry.cpp
Create a new "input" menu for external programs
Create a new "analysis" menu for ssurfaces, QTAIM, etc.
Version 1.1
Suite D4700 …
> Reorganize menus - fix #474

- avogadro/qtplugins/plotpdf/plotpdf.cpp
- avogadro/qtplugins/plotpdf/plotpdf.h
- avogadro/qtplugins/plotrmsd/plotrmsd.cpp
- avogadro/qtplugins/plotrmsd/plotrmsd.h
- avogadro/qtplugins/plotxrd/plotxrd.cpp
- avogadro/qtplugins/plotxrd/plotxrd.h
- avogadro/vtk/vtkplot.cpp
- avogadro/vtk/vtkplot.h
This will allow us to add more customization to the class without
having a static function with an exceedingly long list of arguments...
Version 1.1
Suite D4700
of my …
> Make VtkPlot more object-oriented

- avogadro/qtplugins/openbabel/openbabel.cpp
Not 100% sure on the cause, but this definitely fixes the issue
Version 1.1
Suite D4700
license and I …
> Fix #571 - ensure we read Gaussian files from file, not stream

- avogadro/qtplugins/symmetry/symmetry.cpp
- avogadro/qtplugins/symmetry/symmetrywidget.cpp
- avogadro/qtplugins/symmetry/symmetrywidget.ui
Pretends that dummy atoms are hydrogens, but it works
Also add a "very loose" / sloppy threshold class
Version 1.1
Suite D4700 …
> Fix symmetry detection with dummy atoms (e.g, ferrocene example)

- avogadro/qtplugins/manipulator/manipulator.cpp
- avogadro/qtplugins/manipulator/manipulator.h
First step to full operation of the manipulate tool
Adapts code from https://github.com/cryos/avogadro/pull/852
(Thanks to @csantosbh)
Fixes #519
Version 1.1
Suite D4700
(b) The contribution is based upon previous work that, to the …
> Allow manipulate to rotate selected fragments

- .github/workflows/build_cmake.yml
- avogadro/qtplugins/CMakeLists.txt
- avogadro/qtplugins/svg/CMakeLists.txt
- avogadro/qtplugins/svg/svg.cpp
- avogadro/qtplugins/svg/svg.h
I've added the SVG "ball and stick" export button. following #290 issue. 
Some important notes are:
-  Installing the  svg-qt libs (libqt5svg5-dev)
- The `frustrumCulling` function is too conservative and I don't know exactly why
> Issue 290 export to SVG

- avogadro/qtplugins/insertfragment/CMakeLists.txt
Fixes #611 - thanks to @yurivict
Version 1.1
Suite D4700
license and I have the right under that license …
> Make sure to install crystals directory even when it exists

- avogadro/qtplugins/selectiontool/selectiontool.cpp
- avogadro/qtplugins/selectiontool/selectiontool.h
- avogadro/qtplugins/selectiontool/selectiontoolwidget.ui
I've fixed the two errors from #614, and the enhancement from #452.
- for the bottom-left to top-right: the points where flipped.
- the random selection: the selection computed the bound IDs as atom IDs creating unexpected behaviors.
- Removed the flat property from `selectiontoolwidget.ui` the solution is simple and visual, but if you don't like it I can try a more complex solution. 
Also I added a double click selection, and correct the draw function from disable the camera move.
> Fixes to the selection tools

- avogadro/core/molecule.cpp
- avogadro/core/molecule.h
- avogadro/core/residue.cpp
- avogadro/core/residue.h
- avogadro/io/mmtfformat.cpp
- avogadro/io/mmtfformat.h
- avogadro/io/pdbformat.cpp
- avogadro/io/pdbformat.h
- Allow retrieving all residues (for iterating)
- Mark residues as heterogen (HET / HETATOM)
- Allow retrieving atoms by name (e.g. get the c-alpha)
Version 1.1
Suite D4700
(b) The contribution is based upon previous work that, to …
> Improve residue code

- .github/workflows/build_cmake.yml
Version 1.1
Suite D4700
work with …
> Add a pass to fix OB plugin library paths on Mac

- avogadro/qtplugins/select/select.cpp
- avogadro/qtplugins/select/select.h
Includes by index, by type (e.g. all HOH or HIS)
Also includes HIS57 to select index 57 if it's a HIS
As discussed https://discuss.avogadro.cc/t/select-residues-pdb-structures/2590/3?u=ghutchis
Version 1.1
Suite D4700
(b) The …
> Add select by residue

- avogadro/io/pdbformat.cpp
Also add support for reading CRYST1 records
Version 1.1
Suite D4700 …
> If a chain ID is missing / invalid, skip (to read non-standard PDB)

- avogadro/qtplugins/overlayaxes/CMakeLists.txt
- avogadro/qtplugins/overlayaxes/overlayaxes.cpp
- avogadro/qtplugins/overlayaxes/overlayaxes.h
- avogadro/rendering/glrenderer.cpp
- avogadro/rendering/groupnode.cpp
- avogadro/rendering/groupnode.h
I've moved the "Overlay axis" to the view menu. 
Also I've added an enum tag `UiType` in the `GroupNode` to differentiate between nodes types: UI nodes, Geometry nodes, etc...
Version 1.1
Suite D4700 …
> Move axis to view menu

- avogadro/core/gaussiansettools.cpp
Needs some code for re-ordering CCA-based input & g, h orbitals
Version 1.1
Suite D4700
license and I …
> Fix #602 - use Molden order for f-orbitals

- avogadro/rendering/glrenderer.cpp
Should fix #653 and related.
Thanks to comment on Qt bug reports:
Giuseppe D'Angelo for a related comment:
https://bugreports.qt.io/browse/QTBUG-36739
Version 1.1
Suite D4700
(b) The contribution is based upon previous work that, to …
> On platforms with nvidia drivers, try using glBlendFuncSeparate

- avogadro/qtplugins/openbabel/obfileformat.cpp
Thanks to @drew-parsons should fix #657
Version 1.1
Suite D4700 …
> Make sure to include .smiles in "need to --gen3d"

- avogadro/qtplugins/scriptfileformats/CMakeLists.txt
Version 1.1
Suite D4700
work with …
> Don't install cclib script - which was removed

- avogadro/core/molecule.cpp
Bug raised by @mquevill - delete a non-selected atom
Since deleting atoms renumbers, make sure selected atoms stays
with "swap and pop" form from atom index, etc.
Version 1.1
Suite D4700
(b) The contribution is based upon previous …
> Fix #650 part 2

- avogadro/io/pdbformat.cpp
Code didn't convert between PDB degrees and radians used in UnitCell
Version 1.1
Suite D4700
license and …
> Fix #679 - incorrect PDB unit cells

- avogadro/qtplugins/editor/editor.cpp
Fixes #680 as suggested by @MSoegtropIMC
Version 1.1
Suite D4700 …
> When dragging to create a new atom, use starting coords

- avogadro/qtplugins/symmetry/symmetry.cpp
- avogadro/qtplugins/symmetry/symmetry.h
- avogadro/qtplugins/symmetry/symmetrywidget.cpp
- avogadro/qtplugins/symmetry/symmetrywidget.h
Since the only code using the id field is this, we use
reinterpret_cast on both sides.
Greatly simplifies the code and speeds matching 
(since you don't have to compare coords, etc.)
Version 1.1
Suite D4700 …
> Use libmsym id field (even as a void*) to track atom ids

- avogadro/rendering/curvegeometry.h
- avogadro/rendering/geometryvisitor.cpp
- avogadro/rendering/geometryvisitor.h
- avogadro/rendering/glrenderer.cpp
- avogadro/rendering/glrendervisitor.cpp
- avogadro/rendering/glrendervisitor.h
- avogadro/rendering/povrayvisitor.h
- avogadro/rendering/visitor.h
- avogadro/rendering/vrmlvisitor.h
In the previous PR I forgot to add the `GeometryVisitor::visit` and `GLRenderVisitor::visit` functions for the `CurveGeometry` class where they calculate the zFar/zNear and the render pass respectively, necessary if it can be rendered alone.  
Version 1.1
Suite D4700
have the right to submit it under the …
> Hot fix cartoons cliping

- avogadro/qtplugins/fetchpdb/fetchpdb.cpp
- avogadro/qtplugins/fetchpdb/fetchpdb.h
Save to a temporary file - readString() doesn't seem to work
Version 1.1
Suite D4700 …
> Use MMTF downloads - more efficient than PDB format

- avogadro/qtplugins/licorice/licorice.cpp
- avogadro/qtplugins/licorice/licorice.h
- avogadro/qtplugins/vanderwaals/vanderwaals.cpp
- avogadro/qtplugins/vanderwaals/vanderwaals.h
- avogadro/qtplugins/wireframe/wireframe.cpp
Fixes most of #696
Version 1.1
Suite D4700 …
> Render selected atoms in VdW and licorice modes

- avogadro/qtgui/CMakeLists.txt
- avogadro/qtgui/colorbutton.cpp
- avogadro/qtgui/colorbutton.h
- avogadro/qtplugins/ballandstick/ballandstick.cpp
- avogadro/qtplugins/cartoons/cartoons.cpp
- avogadro/qtplugins/crystal/crystalscene.cpp
- avogadro/qtplugins/crystal/crystalscene.h
- avogadro/qtplugins/wireframe/wireframe.cpp
- avogadro/qtplugins/wireframe/wireframe.h
> Update render options

- avogadro/core/molecule.cpp
- avogadro/io/cjsonformat.cpp
Fixes #707 - thanks to @MSoegtropIMC for the report
Also won't save custom colors to CJSON unless they're set
Version 1.1
Suite D4700
of my knowledge, is covered …
> Make sure to reset colors when changing elements

- avogadro/qtplugins/cartoons/cartoons.cpp
Prevents non-peptides from showing cartoons
Version 1.1
Suite D4700 …
> Require residues for cartoon display

- avogadro/qtplugins/applycolors/applycolors.cpp
- avogadro/qtplugins/applycolors/applycolors.h
Useful for the "rainbow effect" in nanotubes, etc.
Version 1.1
Suite D4700 …
> Apply colors based on distance from atom 1

- .github/release-drafter.yml
Version 1.1
Suite D4700
work with …
> Update release-drafter template to include i18n for Weblate

- avogadro/core/secondarystructure.cpp
Check to make sure atoms are valid before using them
Version 1.1
Suite D4700 …
> Fix crash in 1qlz PDB file from 2nd Structure Assignment

- avogadro/core/layermanager.h
- avogadro/io/cjsonformat.cpp
- avogadro/qtgui/pluginlayermanager.cpp
- avogadro/qtgui/pluginlayermanager.h
- avogadro/qtplugins/ballandstick/ballandstick.cpp
- avogadro/qtplugins/cartoons/cartoons.cpp
- avogadro/qtplugins/label/label.cpp
- avogadro/qtplugins/wireframe/wireframe.cpp
The plugins are only created once and the load is never called when the files are opened. 
I've fixed that and added a set to avoid reloading multiple times.
Version 1.1
Suite D4700
(b) The contribution is based upon previous …
> Fix load settings

- avogadro/core/atom.h
- avogadro/core/molecule.h
- avogadro/qtgui/pluginlayermanager.cpp
- avogadro/qtgui/pluginlayermanager.h
- avogadro/qtgui/rwmolecule.cpp
- avogadro/qtgui/rwmolecule.h
- avogadro/qtgui/rwmolecule_undo.h
- avogadro/qtplugins/editor/editor.cpp
- avogadro/qtplugins/editor/editor.h
- avogadro/qtplugins/select/select.cpp
- avogadro/qtplugins/select/select.h
- avogadro/qtplugins/selectiontool/selectiontool.cpp
- avogadro/qtplugins/selectiontool/selectiontool.h
- avogadro/qtplugins/selectiontool/selectiontoolwidget.cpp
- avogadro/qtplugins/selectiontool/selectiontoolwidget.h
- avogadro/qtplugins/selectiontool/selectiontoolwidget.ui
- Locking a layer deny select atom in it.
- Easy way to select and change the atom layer (ctrl+x and ctrl+v was too slow), and also includes do/undo. 
- do/undo in atom coloring
Version 1.1
Suite D4700 …
> Improve in selection tool

- avogadro/qtplugins/scriptfileformats/fileformatscript.cpp
- avogadro/qtplugins/scriptfileformats/fileformatscript.h
Version 1.1
Suite D4700
work with …
> Enable script formats like cclib to ask for bond perception on read

- avogadro/qtplugins/apbs/apbs.cpp
- avogadro/qtplugins/cp2kinput/cp2kinput.cpp
- avogadro/qtplugins/gamessinput/gamessinput.cpp
- avogadro/qtplugins/lammpsinput/lammpsinput.cpp
- avogadro/qtplugins/openmminput/openmminput.cpp
- avogadro/qtplugins/quantuminput/quantuminput.cpp
Version 1.1
Suite D4700
work with …
> Add "..." to all input generators to indicate opening a dialog

- avogadro/qtplugins/copypaste/copypaste.cpp
Not sure why this wasn't flagged earlier - easy fix
Version 1.1
Suite D4700 …
> Fix compile error on clang-10

- avogadro/qtplugins/playertool/playertool.cpp
Fix #762 temporarily - likely a race condition with
clearing and creating bonds. For now, let's not crash.
Version 1.1
Suite D4700
of my knowledge, is covered under …
> Disable dynamic bonding during animation

- avogadro/qtgui/pythonscript.cpp
- avogadro/qtgui/utilities.cpp
- avogadro/qtgui/utilities.h
Should fix #742 - at least on Mac. Not sure on Windows yet.
Version 1.1
Suite D4700 …
> Try to use 'python' in the path as a fallback

- avogadro/qtgui/pluginlayermanager.cpp
- avogadro/qtgui/sceneplugin.h
- avogadro/qtplugins/ballandstick/ballandstick.h
- avogadro/qtplugins/cartoons/cartoons.h
- avogadro/qtplugins/label/label.h
- avogadro/qtplugins/licorice/licorice.h
- avogadro/qtplugins/vanderwaals/vanderwaals.h
- avogadro/qtplugins/vanderwaalsao/vanderwaalsao.h
- avogadro/qtplugins/wireframe/wireframe.h
Added `ScenePlugin::defaultBehavior` to know if a plugin should be True/False or just ignored as a default behavior. 
Also, roll back in the previous try. 
This is related to: https://github.com/OpenChemistry/avogadroapp/pull/235
Version 1.1
Suite D4700
have the right to submit it under the open source …
> Default behavior check

- tests/core/unitcelltest.cpp
Unit test UnitCellTest.wrapAtomsToUnitCell fails on i386 (i686):
[ RUN      ] UnitCellTest.wrapAtomsToUnitCell
/tmp/autopkgtest-lxc.w4hysxt4/downtmp/build.1Hw/src/tests/core/unitcelltest.cpp:265: Failure
Expected: (it->y()) >= (static_cast<Real>(0.0)), actual: -1.44334e-18 vs 0
[  FAILED  ] UnitCellTest.wrapAtomsToUnitCell (0 ms)
Evidently the precision is too tight for 32-bit i386, such that it->y() is "mostly zero" but crosses just below 0, making the test fail.
Replacing the test ">=0" with ">-EPS" enables the test to pass on i386.
Fixes Issue #812.
Version 1.1
Suite D4700 …
> test ">=0" within machine precision (>-EPS)

- avogadro/qtgui/rwmolecule_undo.h
This fixes the regression described at https://github.com/OpenChemistry/avogadroapp/issues/239. This issue appeared with https://github.com/OpenChemistry/avogadrolibs/commit/d2dcfaead5080597c877246a7253c483f7668c3c, due to a small change in `avogadro/qtgui/rwmolecule_undo.h` wherein `RWMolecule::addAtom()` was made to be passed `m_atomId` rather than `m_atomUid`, when it should expect a UID.
The consequence was that, when two carbons were bonded and their hydrogens adjusted, the hydrogens on one of the carbons would be removed and not be added back, due to the passed UIDs actually being their IDs, which happened to be equal to the removed hydrogens' UIDs.
Then, trying to add atoms around this molecule with 5 atoms would pass atom ID 5 as UID, this being the UID of one of the existing …
> Fix erratic editing behavior

- .github/workflows/build_cmake.yml
Previous build failure looks like it's just a temporary
Version 1.1
Suite D4700 …
> Switch to 5.12.12 release

- avogadro/qtplugins/bondcentrictool/bondcentrictool.cpp
- avogadro/qtplugins/manipulator/manipulator.cpp
> Fix Manipulation and Bond Centric Manipulation tools

- avogadro/io/pdbformat.cpp
This is a small fix for the PDB importer not recognizing 2-letter element symbols. PDB files contain those symbols written in all caps, while Avogadro expects the second letter to be lowercase.
Version 1.1
Suite D4700 …
> Convert 2-letter PDB symbols to appropriate case

- avogadro/core/molecule.cpp
This Pull Requests implements a new bond perception algorithm that is O(n) in the average case, down from O(n²). Among other probable improvements, this represents 5 - 15 times faster PDB import, making the Avogadro PDB path faster than Open Babel.
While the previous code tested every possible pair of atoms in a molecule, this new version first puts atoms in a 3D array of cubic bins with side equal to twice the maximum covalent radius plus tolerance, then only checks each atom against other atoms inside its bin and those in a 3D Moore neighborhood. For valid molecules, the number of operations performed must be, on average, linear to the number of atoms.
Version 1.1
Suite …
> Faster bond perception

- avogadro/core/molecule.cpp
- avogadro/core/molecule.h
- avogadro/io/cjsonformat.cpp
- avogadro/io/cmlformat.cpp
- avogadro/io/mdlformat.cpp
- avogadro/io/mdlformat.h
- avogadro/io/pdbformat.cpp
- avogadro/io/pdbformat.h
- avogadro/qtgui/rwmolecule.cpp
This Pull Requests improves Avogadro's support for formal charges. First of all, it implements reading them from CML, which also extends to other formats (e.g. SMILES, which is internally converted to CML). Those charges are then passed down the class hierarchy. Secondly, since PDB files can contain quaternary ammonium (e.g. acetylcholine, various drug ligands) or tertiary sulfonium (S-adenosylmethionine), or even quaternary arsonium (https://www.rcsb.org/structure/5NXY) groups, and those cannot be eliminated by hydrogen adjustment, specific code was added to detect those.
Then, the code was made more convergent with other paths so as to allow the various optimization PRs to act on it.
Version 1.1
Copyright (C) 2004, 2006 The Linux Foundation and its …
> Formal charges

- avogadro/qtplugins/propertytables/propertymodel.cpp
- avogadro/qtplugins/propertytables/propertymodel.h
Fix #838 - adding edit in another pull request
Version 1.1
Suite D4700 …
> Add formal charge to atom property tables

- avogadro/qtgui/fileformatdialog.cpp
- avogadro/qtgui/fileformatdialog.h
- For common extensions, use only one extension in the filter
- Add better error message if an extension is missing
Version 1.1
Suite D4700 …
> Solve problems writing files with no extension

- avogadro/qtplugins/openbabel/openbabel.cpp
Make sure the string matches exactly - should work now
Version 1.1
Suite D4700 …
> Fix #827 - reading generic file formats with Open Babel

- .github/workflows/build_wheels.yml
Windows 2016 is deprecated and not available on GH runners
Instead let's switch to Windows 2019
Version 1.1
Suite D4700 …
> Try using Windows 2019 to build wheels

- avogadro/rendering/bsplinegeometry.cpp
~17 lines changed, 3x faster load time to full cartoon view for `1aco.pdb`, probably higher for larger proteins. Down from 44 to 15 seconds on my machine.
Version 1.1
Suite D4700
(b) The contribution is based upon previous work that, to the …
> Approximate B-spline from a small local neighborhood

- avogadro/core/connectedgroup.cpp
- avogadro/core/graph.cpp
- avogadro/core/graph.h
- avogadro/core/molecule.cpp
- avogadro/core/molecule.h
- avogadro/qtgui/rwmolecule.h
This Pull Request gives a big boost to many Molecule operations. It should make PDB import almost twice as fast (relative to #829), and hydrogen adjustment 15 times faster for macromolecules.
It adds a new member to `Core::Molecule`, a vector of vectors containing the bond indices associated with each particular atom in the molecule. This information could only be obtained in O8n) time, while now it should be O(1). This data is updated in parallel with `m_graph`.
Version 1.1
Suite D4700
By …
> Bond graph optimization

- avogadro/qtgui/sceneplugin.cpp
- avogadro/qtgui/sceneplugin.h
- avogadro/qtopengl/glwidget.cpp
- avogadro/qtopengl/glwidget.h
- avogadro/qtplugins/crystal/crystalscene.cpp
- avogadro/qtplugins/crystal/crystalscene.h
- avogadro/qtplugins/force/force.cpp
- avogadro/qtplugins/force/force.h
- avogadro/qtplugins/label/label.cpp
- avogadro/qtplugins/label/label.h
- avogadro/qtplugins/meshes/meshes.cpp
- avogadro/qtplugins/meshes/meshes.h
- avogadro/qtplugins/qtaim/qtaimengine.cpp
- avogadro/qtplugins/qtaim/qtaimengine.h
- avogadro/qtplugins/surfaces/surfaces.cpp
- avogadro/qtplugins/symmetry/symmetryscene.cpp
- avogadro/qtplugins/symmetry/symmetryscene.h
Fixes crashes after generating surface meshes (on Mac at least)
.. the Core::Molecule cast would get deleted and a race occurred
Version 1.1
Suite D4700
of my …
> Remove call for Core::Molecule rendering to eliminate casting

- avogadro/rendering/cylindergeometry.cpp
- avogadro/rendering/linestripgeometry.cpp
- avogadro/rendering/shaderprogram.cpp
- avogadro/rendering/spheregeometry.cpp
- avogadro/rendering/textlabelbase.cpp
Background:  
I had issues with Avogadro crashing after some minutes when I was viewing vibrational modes, and I quickly realized it was because Avogadro continually allocated more memory until my RAM+swap was full.
From what I understand, this is because each geometry update (for each animation frame) will trigger `GLWidget::updateScene()`, which clears the rendering `GroupNode` (https://github.com/OpenChemistry/avogadrolibs/blob/master/avogadro/qtopengl/glwidget.cpp#L82) and then rebuilds. During that clearing, the `ShaderProgram` objects get destroyed, however they are not being deleted from OpenGL.
Changing this alone however doesn't fix the issue, so I also added code to detach and delete the shader as soon as `glLinkProgram()` was called (Following [this …
> OpenGL: Detaching and deleting shaders/programs on updates

- avogadro/core/molecule.cpp
- avogadro/core/spacegroups.cpp
- avogadro/core/spacegroups.h
- avogadro/io/cmlformat.cpp
- avogadro/io/cmlformat.h
- avogadro/io/mmtfformat.cpp
- avogadro/qtplugins/spacegroup/spacegroup.cpp
- avogadro/qtplugins/spacegroup/spacegroup.h
> Import and retain space group information

- avogadro/qtplugins/overlayaxes/overlayaxes.cpp
- avogadro/rendering/camera.cpp
- avogadro/rendering/glrenderer.cpp
- avogadro/rendering/shaderprogram.cpp
A small change, but it's necessary if a Valgrind CI test is eventually put in place. Now something like `valgrind --tool=memcheck --error-exitcode=1 ./avogadrolibs/bin/AvogadroTests` should work as expected (e.g. right now all tests exit with zero status, except `AvogadroQtGuiTests`, which detects 2 unitialized value errors).
Version 1.1
Suite D4700
(a) The contribution was created in …
> Fix Valgrind uninitialized errors

- avogadro/qtgui/rwmolecule.cpp
Tracked down the last uninitialized value error to get Valgrind working with tests. Now all of them should exit with zero status code when run with `valgrind --tool=memcheck --error-exitcode=1`.
Version 1.1
Suite D4700
(b) The contribution …
> Fix remaining errors in tests

- .github/workflows/build_cmake.yml
Reverts OpenChemistry/avogadrolibs#885
We need to use the CPACK_PRE_BUILD_SCRIPTS in `avogadroapp` to sign. Right now, the signature is broken, which is worse than no signature.
> Revert "Use signed mac package"

- avogadro/core/neighborperceiver.cpp
- avogadro/core/neighborperceiver.h
- tests/core/CMakeLists.txt
- tests/core/neighborperceivertest.cpp
This is a bug I found while working on the still in-progress surface code. It prevents calculating part of the surface, but is generally an issue for any consumer of the `NeighborPerceiver` API.
Version 1.1
Suite D4700
of my …
> Fix NeighborPerceiver not handling coordinates below the minimum

- avogadro/qtplugins/ballandstick/ballandstick.cpp
- avogadro/qtplugins/cartoons/cartoons.cpp
- avogadro/qtplugins/label/label.cpp
- avogadro/qtplugins/qtaim/qtaimlsodaintegrator.cpp
- avogadro/qtplugins/wireframe/wireframe.cpp
Version 1.1
Suite D4700
work with …
> Minor cleanups using clang-tidy nullptr, override

- avogadro/core/molecule.cpp
- avogadro/core/neighborperceiver.cpp
- avogadro/core/neighborperceiver.h
- tests/core/neighborperceivertest.cpp
`getNeighbors` has been renamed to `getNeighborsInclusive`. I'm wondering if a `getNeighbors` (exclusive) would be welcome, as it would simply need to keep a copy of the input array and use it to decide what neighbors to actually return. The functions have also been made somewhat faster (at least 30%) and a new `getNeighborsInclusiveInPlace` has been added, which returns neighbors in an array passed as parameter rather than returning a newly allocated array, which could amount to many thousands of allocations.
Version 1.1
Suite D4700
Everyone is permitted to copy and distribute verbatim copies of …
> Update NeighborPerceiver (better naming, optimization)

- avogadro/qtgui/layermodel.cpp
- avogadro/qtgui/molecule.h
- avogadro/qtgui/rwlayermanager.cpp
- avogadro/qtplugins/select/select.cpp
- avogadro/qtplugins/select/select.h
- avogadro/qtplugins/selectiontool/selectiontool.cpp
- avogadro/qtplugins/selectiontool/selectiontool.h
- avogadro/qtplugins/selectiontool/selectiontoolwidget.cpp
- avogadro/qtplugins/selectiontool/selectiontoolwidget.h
Draft to create a new layer from a selection (e.g., select a bunch of water molecules, hide them)
- Creates a new layer
- Sets the render types in the new layer to the same set from the active layer
- Moves the selected atoms into the new layer
Still needs:
This should probably move the code from `selectiontool.cpp` into the RWLayerManager for "cloneNewLayer()` or something similar.
It might also be worth just adding this to the default RWLayerManager `addLayer()` method to reduce surprise (e.g., create a new layer that defaults to the same render types as the active layer).
Version 1.1
Suite D4700
Everyone is permitted to copy and distribute …
> Create new layer from selection

- avogadro/qtplugins/insertdna/insertdna.cpp
Causes occasional crashes when opening the new 'Insert DNA/RNA' dialog on my machine.
Version 1.1
Suite D4700 …
> Fix uninitialized error in InsertDna

- avogadro/qtplugins/closecontacts/closecontacts.cpp
Don't show a close contact when either atom is not enabled. Should be as fast as before.
Version 1.1
Suite D4700 …
> Make close contact perception respect visible layers

- avogadro/quantumio/gamessus.cpp
- avogadro/quantumio/nwchemlog.cpp
The GAMESS-US and NWChem-log output readers now raise an error if they could not read any atomic coordinates from the output. Also make the return value nodiscard to force callers to check if the read actually succeeded, as these functions also alter the state of a Molecule object if the read succeeds differently than in case of a failure.
Partially resolves issue 2. in https://discuss.avogadro.cc/t/molpro-import-is-still-regressed-in-avogadro2-1-96-0-compared-to-avogadro1/3855
Version 1.1
Suite D4700
Developer's Certificate of …
> GAMESS-US and NWChem output reader sanity check

- avogadro/qtplugins/openbabel/obfileformat.cpp
- avogadro/qtplugins/openbabel/obfileformat.h
- avogadro/qtplugins/openbabel/obforcefielddialog.cpp
- avogadro/qtplugins/openbabel/obforcefielddialog.h
- avogadro/qtplugins/openbabel/obprocess.cpp
- avogadro/qtplugins/openbabel/obprocess.h
- avogadro/qtplugins/openbabel/openbabel.cpp
- avogadro/qtplugins/openbabel/openbabel.h
Version 1.1
Suite D4700
work with …
> Check for Open Babel CJSON support: use it if available

- avogadro/core/bond.h
- avogadro/qtplugins/noncovalent/noncovalent.cpp
So, this PR implements some functionality that doesn't yet depend on `generateNewBondVector`. It computes the angle between the vector connecting both H-bonded atoms and the antipodes of all bond vectors to the pair acceptor (the 'holes'). If any of them produce an angle smaller than the specified tolerance, the bond is accepted.
As a consequence, only relatively "real" hydrogen bonds will be shown, which means that just adding hydrogens to an imported macromolecule will not produce as many of these bonds at random.
Version 1.1
Suite D4700
Everyone is permitted to copy and distribute verbatim …
> Make use of angle tolerance for hole detection

- avogadro/core/CMakeLists.txt
- avogadro/core/atomutilities.cpp
- avogadro/core/atomutilities.h
- avogadro/qtgui/hydrogentools.cpp
- avogadro/qtgui/hydrogentools.h
This moves `perceiveHybridization` and `generateNewBondVector` into a new class named `AtomUtilities`. The new interface accepts a `Core::Molecule` rather than the original `QtGui::RWMolecule`.
Version 1.1
Suite D4700 …
> Move some HydrogenTools code into AtomUtilities

- avogadro/qtplugins/noncovalent/noncovalent.cpp
- avogadro/qtplugins/noncovalent/noncovalent.h
Version 1.1
Suite D4700
work with …
> Add line widths to the non-covalent / h-bond rendering

- avogadro/core/atomutilities.cpp
- avogadro/core/atomutilities.h
- avogadro/qtplugins/noncovalent/noncovalent.cpp
This works well with sp, sp2 and sp3 hybridization, and any number of bonds, on the acceptor atom. If a different hybridization is present, the bond will be accepted.
Version 1.1
Suite D4700
(b) The contribution is based upon previous work …
> Add electron pair angle check for hydrogen bonds

- avogadro/qtplugins/closecontacts/closecontacts.cpp
- avogadro/qtplugins/noncovalent/noncovalent.cpp
- avogadro/qtplugins/noncovalent/noncovalent.h
It adds both halogen and chalcogen bonds, which are displayed under some pretty arbitrary conditions (must have look at it eventually). I also increased the default angle tolerance to 40 degrees, and distance to 3.0 Å, and changed close contacts' color to a shade of gray so it contrasts more easily with the new types of bonds.
Version 1.1
Suite D4700
(a) The contribution was created in …
> Add halogen and chalcogen bonds, tune parameters

- avogadro/qtplugins/surfaces/gaussiansetconcurrent.cpp
- avogadro/qtplugins/surfaces/slatersetconcurrent.cpp
- avogadro/qtplugins/surfaces/slatersetconcurrent.h
- avogadro/qtplugins/surfaces/surfacedialog.cpp
- avogadro/qtplugins/surfaces/surfacedialog.h
- avogadro/qtplugins/surfaces/surfaces.cpp
- avogadro/qtplugins/surfaces/surfaces.h
- avogadro/qtplugins/symmetry/symmetryscene.h
- avogadro/vtk/vtkAvogadroActor.cxx
- avogadro/vtk/vtkAvogadroActor.h
- avogadro/vtk/vtkglwidget.cpp
- avogadro/vtk/vtkglwidget.h
- avogadro/vtk/vtkplot.cpp
- avogadro/vtk/vtkplot.h
Version 1.1
Suite D4700
work with …
> Fix some inconsistent overrides and headers

- avogadro/qtplugins/noncovalent/noncovalent.cpp
Just a small PR to add S, Se, Te as acceptors for chalcogen bonds. Proper support also probably requires setting different maximum distance and angle tolerance from that of hydrogen bonds, but that'll go in a separate PR along with the GUI code.
Version 1.1
Suite D4700
have the right to submit it under the open source …
> Add missing acceptors and make distance relative (non-covalent)

- avogadro/qtplugins/noncovalent/noncovalent.cpp
- avogadro/qtplugins/noncovalent/noncovalent.h
It features independent angle tolerances and distances for every bond type, with one single line width value. It doesn't yet have options to disable individual types or change their color.
Version 1.1
Suite D4700 …
> Implement basic tabbed interface for NonCovalent

- avogadro/core/mesh.cpp
- avogadro/qtplugins/surfaces/surfacedialog.cpp
- avogadro/qtplugins/surfaces/surfacedialog.h
- avogadro/qtplugins/surfaces/surfacedialog.ui
- avogadro/qtplugins/surfaces/surfaces.cpp
- avogadro/qtplugins/surfaces/surfaces.h
This PR adds:
* An "Automatic" resolution for surfaces, which chooses an appropriate resolution for the current molecule.
* A "Smoothing Passes" widget within the surfaces UI. Setting to zero passes disables smoothing and makes the operation faster.
* An optimization to the smoothing code: setting the maximum `NeighborPerceiver` distance to half its value. This makes it fast enough in most cases (still the main bottleneck), while constraining the largest mesh that can be smoothed without running into RAM limits ("typical" proteins seem to run fine, but I can't process e.g. a whole ribosome). I plan on doing a more targeted optimization in the future, but this should allow actually using the new code for now.
Developer Certificate of …
> Add "Automatic" resolution, smoothing pass UI, optimization

- avogadro/calc/chargemanager.cpp
- avogadro/calc/chargemanager.h
- avogadro/calc/chargemodel.cpp
- avogadro/calc/chargemodel.h
- avogadro/calc/defaultmodel.cpp
- avogadro/qtplugins/openbabel/CMakeLists.txt
- avogadro/qtplugins/openbabel/obcharges.cpp
- avogadro/qtplugins/openbabel/obcharges.h
- avogadro/qtplugins/openbabel/obprocess.cpp
- avogadro/qtplugins/openbabel/obprocess.h
- avogadro/qtplugins/openbabel/openbabel.cpp
- avogadro/qtplugins/openbabel/openbabel.h
Required removing const for molecules on multiiple methods
but it's worth it (e.g., save the Gasteiger or MMFF charges)
Version 1.1
Suite D4700 …
> Enable Open Babel charge models, including caching partial charges

- avogadro/qtgui/layermodel.cpp
- avogadro/qtgui/layermodel.h
- avogadro/qtplugins/vanderwaals/vanderwaals.h
- avogadro/qtplugins/vanderwaalsao/vanderwaalsao.h
Version 1.1
Suite D4700
work with …
> Make sure that render names in the layer list show up w/ i18n

- avogadro/core/molecule.cpp
- avogadro/qtplugins/openbabel/obcharges.cpp
> Workaround charge models locking up or not running

- avogadro/qtplugins/closecontacts/closecontacts.cpp
This displays interactions between oppositely charged atoms, as well as same-charge ("bad contacts"). Charged residues with no real formal charge in the molecule are also interpreted as charged.
Version 1.1
Suite D4700
(b) The contribution …
> Initial salt bridge implementation

- avogadro/molequeue/inputgeneratorwidget.cpp
Fix #924 - do not attempt to open the default file name
Also disable the "Submit calculation" if Molequeue is not running
Version 1.1
Suite D4700 …
> Fix two minor input generator bugs

- avogadro/qtgui/jsonwidget.cpp
- avogadro/qtgui/jsonwidget.h
Previously would use the translated string for a key
(e.g., Cím in Hungarian instead of "Title")
Version 1.1
Suite D4700 …
> Fix input generators (and other scripts) with translation

- avogadro/qtplugins/scriptcharges/chargeScripts/antechamber.py
- avogadro/qtplugins/scriptcharges/chargeScripts/xtb.py
fix #1034
Signed-off-by: Eisuke Kawashima <e-kwsm@users.noreply.github.com>
Version 1.1
Suite D4700 …
> clarify error messages of chargeScripts when antechamber or xtb is unavailable

- docs/CMakeLists.txt
Version 1.1
Suite D4700
work with …
> Fix CMake error with missing conf.py.in [skip-ci]

- avogadro/io/pdbformat.cpp
- tests/io/CMakeLists.txt
- tests/io/pdbtest.cpp
Polishes the functionality introduced by #1047, by introducing a test and fixing an issue.
Version 1.1
Suite D4700 …
> Add test and fix PDB AltLoc support accordingly

- avogadro/qtgui/rwmolecule.cpp
- avogadro/qtgui/rwmolecule.h
- avogadro/qtgui/rwmolecule_undo.h
- avogadro/qtplugins/propertytables/propertyview.cpp
- avogadro/qtplugins/select/select.cpp
- avogadro/qtplugins/selectiontool/selectiontool.cpp
Fix #220
Version 1.1
Suite D4700
work with …
> Add support for undo/redo selections, including custom menu text.

- avogadro/core/molecule.cpp
- avogadro/core/molecule.h
- avogadro/io/cjsonformat.cpp
Further support needed in input generators, etc.
Version 1.1
Suite D4700 …
> Initial support for total charge and spin through CJSON.

- avogadro/core/neighborperceiver.cpp
- avogadro/core/neighborperceiver.h
This avoids recomputing the output array of `getNeighborsInclusiveInPlace` whenever it's unnecessary. The actual performance gain for something like surface generation is just 0 - 5%, but this is a pretty small change and affects multiple code paths.
Version 1.1
Suite D4700
have the right to submit it under the open source …
> Optimize NeighborPerceiver

- avogadro/qtplugins/navigator/navigator.cpp
According to the [Qt5 docs](https://doc.qt.io/qt-5/qwheelevent.html#pixelDelta) it's unreliable on this platform.
Could fix #1064, which is a 1.96 regression.
Version 1.1
Suite D4700
(b) The contribution is based upon previous work that, to …
> Avoid using QWheelEvent::pixelDelta() on X11

- avogadro/qtplugins/bondcentrictool/bondcentrictool.cpp
- avogadro/qtplugins/symmetry/symmetryscene.cpp
- avogadro/rendering/CMakeLists.txt
- avogadro/rendering/arcsector.cpp
- avogadro/rendering/arcsector.h
- avogadro/rendering/arcstrip.cpp
- avogadro/rendering/arcstrip.h
- avogadro/rendering/quad.cpp
- avogadro/rendering/quad.h
- avogadro/rendering/quadoutline.cpp
- avogadro/rendering/quadoutline.h
These were hidden away and not obvious for shared use
Version 1.1
Suite D4700 …
> Move arc and quad mesh and linestrip convenience classes

- avogadro/qtplugins/templatetool/templatetool.cpp
- avogadro/qtplugins/templatetool/templatetoolwidget.cpp
- avogadro/qtplugins/templatetool/templatetoolwidget.h
- avogadro/qtplugins/templatetool/templatetoolwidget.ui
Just a small PR to add a formal charge selection feature to the new template tool. Formal charges are currently 0 to +7.
Version 1.1
Suite D4700 …
> Add formal charge combobox to template tool

- avogadro/qtplugins/templatetool/templatetool.cpp
- avogadro/qtplugins/templatetool/templatetoolwidget.cpp
- avogadro/qtplugins/templatetool/templatetoolwidget.h
* Wrong atoms being bonded sometimes, especially with groups.
* Some hydrogens not being removed, a chance to remove wrong atoms under some conditions.
* Zero-rotation (e.g. aqua to a tetrahedral center) sometimes making the molecule disappear.
* Half-rotation potentially having the same effect, by a different mechanism.
Version 1.1
Suite D4700
have the right to submit it …
> Fix a few more issues with templates

- avogadro/qtplugins/templatetool/templatetool.cpp
> Estimate bond distances in template tool

- avogadro/qtplugins/molecularproperties/molecularpropertiesdialog.cpp
- avogadro/qtplugins/molecularproperties/molecularpropertiesdialog.h
- avogadro/qtplugins/molecularproperties/molecularpropertiesdialog.ui
Fix #342
Version 1.1
Suite D4700
work with …
> Fetch molecule names from PubChem PUG interface

- avogadro/qtplugins/wireframe/wireframe.cpp
Previously, no AtomType rendering was presented.
Fix #1127
Version 1.1
Suite D4700 …
> Add atoms for selection in wireframe rendering

- avogadro/rendering/povrayvisitor.cpp
Actually writes the mesh (which was computed but never written) Fix export of texture colors, including transparency
Version 1.1
Suite D4700 …
> Fix POV-Ray mesh export

- avogadro/qtplugins/ballandstick/ballandstick.cpp
Orthogonal unit vector always seems to be in the XY plane
I'll clean this up a bit so it doesn't have weird constants
Version 1.1
Suite D4700 …
> Tweak rendering multiple bonds, rotate 45 degree angle

- python/CMakeLists.txt
With this change it builds both as an option of the overall avogadrolibs project and as a standalone project.
Version 1.1
Suite D4700 …
> Make Python bindings build as a standalone project

- avogadro/rendering/ambientocclusionspheregeometry.cpp
- avogadro/rendering/spheregeometry.cpp
Firstly, NULL isn't strictly defined in modern C++ and it can be defined as "0".
Secondly, clang fails on 'reinterpret_cast<const GLvoid*>(nullptr)':
error: reinterpret_cast from 'std::nullptr_t' to 'const GLvoid *' (aka 'const void *') is not allowed
Version 1.1
Suite D4700
(b) The …
> Fix build with clang: reinterpret_cast<const GLvoid*>(NULL)

- .github/workflows/clang-format-check.yml
clang-format-6.0 is no longer available on latest
ubuntu.
Signed-off-by: Stefan Brüns <stefan.bruens@rwth-aachen.de>
Version 1.1
Suite D4700 …
> Use a more recent clang-format

- avogadro/qtplugins/scriptfileformats/fileformatscript.cpp
Version 1.1
Suite D4700
work with …
> Perceive bond orders when requested by Python scripts

- .github/workflows/clang-format-check.yml
> ci: use `${{github.ref}}` and `if`

- avogadro/qtplugins/label/label.cpp
https://discuss.avogadro.cc/t/atom-label-system/4422
Version 1.1
Suite D4700 …
> Fix atom index labels to start with 1, not zero as users expect

- avogadro/vtk/vtkplot.cpp
This is very hackish, but it allows you to see the plot. The main issue is that this should have always been in a dialog or similar with a layout. The way that VTK interacts with Qt has changed and so the size being set does not appear to act as it once did. Issue #1107.
> Ensure the VTK plot widget has a minimum size

- .github/workflows/build_m1.yml
> Fix base64 syntax for signing certificate on Mac

- .github/workflows/build_m1.yml
> Allow continue-on-error for notarization

- avogadro/qtplugins/plotxrd/CMakeLists.txt
We shouldn't download things during build by default. Ideally this would get packaged or added as a step in the superbuild. Fixes issue #1186 by defaulting to expect a system binary.
> Advanced option to use the system generateXrd

- .github/workflows/codacy.yml
Convert it to a workflow manual option
(Generally, this is very high noise anyway)
> Temporarily disable Codacy scan

- avogadro/core/ringperceiver.cpp
- avogadro/qtplugins/cp2kinput/cp2kinputdialog.cpp
- avogadro/qtplugins/scriptcharges/scriptchargemodel.cpp
- avogadro/qtplugins/symmetry/symmetry.cpp
- avogadro/qtplugins/symmetry/symmetrywidget.cpp
- utilities/resdata/resdataparse.cxx
There are a few more related to Qt where `length()` methods return `int` that I didn't touch under the assumption that Qt 6 may change things.
---
Version 1.1
Suite D4700 …
> Fix some compiler warnings not related to Qt

- avogadro/qtgui/extensionplugin.cpp
- avogadro/qtgui/extensionplugin.h
- avogadro/qtgui/toolplugin.cpp
- avogadro/qtgui/toolplugin.h
- avogadro/qtplugins/spectra/spectra.cpp
- avogadro/qtplugins/spectra/spectra.h
First example is with the spectra plugin to show / set vibrations Also, now show displacement arrows with the force visualizer
Version 1.1
Suite D4700
license and I …
> Add extension and tool register / handle commands for scripts

- avogadro/io/cjsonformat.cpp
- avogadro/quantumio/gaussianfchk.cpp
- avogadro/quantumio/molden.cpp
> chemicaljson enhancements

- avogadro/core/mdlvalence_p.h
- tests/qtgui/hydrogentoolstest.cpp
Fix #1201 - only allow valence of 5 if there's a nitro group
Version 1.1
Suite D4700
work with …
> Adjust nitrogen valence determination

- .github/workflows/build_cmake.yml
Should workaround Ubuntu bug:
https://bugs.launchpad.net/ubuntu/+source/gcc-9/+bug/2029910
Version 1.1
Suite D4700
license and I have the right under that license …
> Turn off leak and thread sanitizer builds for now

- avogadro/qtgui/pythonscript.cpp
- avogadro/qtgui/scriptloader.cpp
- avogadro/qtplugins/scriptcharges/chargeScripts/antechamber.py
- avogadro/qtplugins/scriptcharges/chargeScripts/xtb.py
Fix #1323 - now indicates Cannot load script /path/to/antechamber.py Also enables i18n of script loader strings
Version 1.1
Suite D4700 …
> Give better warnings when scripts do not load

- avogadro/qtplugins/openbabel/openbabel.cpp
Fix #1324 by ignoring MMFF94 support for iron, etc. (MMFF94 only supports isolated ions.)
Version 1.1
Suite D4700 …
> Fix autodetect for force field with inorganic complexes

- .github/workflows/build_cmake.yml
- .github/workflows/build_m1.yml
Uses current notarytool protocol - should be good on new Xcode
Version 1.1
Suite D4700
work with …
> Update Mac notarization procedure to skip npm package

- .github/workflows/build_cmake.yml
- .github/workflows/build_m1.yml
Also will continue on error if notarytool fails
(It just means users need a network connection to validate.)
Version 1.1
Suite D4700 …
> Add team-id secret for Mac notarytool

- python/core.cpp
- python/io.cpp
> More pybind methods and properties

- avogadro/core/cube.h
- avogadro/qtplugins/surfaces/surfaces.cpp
- avogadro/qtplugins/surfaces/surfaces.h
Needs testing to make sure dialog isn't required
Version 1.1
Suite D4700 …
> Initial support for scripting surface generation

- avogadro/core/coordinateblockgenerator.cpp
- avogadro/core/dihedraliterator.cpp
- avogadro/core/elements.cpp
- avogadro/io/gromacsformat.cpp
- avogadro/io/lammpsformat.cpp
- avogadro/io/pdbformat.cpp
- avogadro/io/turbomoleformat.cpp
- avogadro/qtplugins/cp2kinput/cp2kinput.h
- avogadro/qtplugins/focus/focus.h
- avogadro/qtplugins/force/force.h
- avogadro/qtplugins/gamessinput/gamessinput.h
- avogadro/qtplugins/templatetool/templatetool.cpp
> Fix codeql warnings

- .github/workflows/build_cmake.yml
- .github/workflows/build_m1.yml
- avogadro/core/molecule.cpp
> Don't bond Noble gases

- avogadro/qtplugins/insertfragment/insertfragmentdialog.cpp
> Re-enable CML fragments in case someone has old files

- avogadro/io/fileformat.cpp
- avogadro/io/fileformat.h
- avogadro/qtgui/fileformatdialog.cpp
> Validating filenames before opening files for read / write

- avogadro/core/angleiterator.cpp
Regarding issue #1346 
Version 1.1
Suite D4700
work with modifications, whether created in whole or …
> Removed !valid from the condition since it always returns false

- avogadro/core/spacegroups.cpp
- avogadro/core/spacegroups.h
> Make sure "fill unit cell" generates copies on the unit cell too

- avogadro/quantumio/gaussianfchk.cpp
- avogadro/quantumio/gaussianfchk.h
> Reading Gaussian fchk vibrations when present

- avogadro/core/molecule.cpp
regarding issue #1346 
Version 1.1
Suite D4700
work with modifications, whether created in whole or …
> removed a clang tidy warning about implicit narrowing conversion

- avogadro/calc/chargemodel.cpp
regarding issue #1346 using clang-tidy
Version 1.1
Suite D4700
work with modifications, whether …
> changes regarding use of constexpr in case of constant variables

- avogadro/qtplugins/surfaces/surfaces.cpp
> Minor fix for scripting orbital rendering - allow integers

- avogadro/io/dcdformat.cpp
Issue #1346 
macro replacement list should be enclosed in parentheses
macro 'DCD_MAGIC' used to declare a constant; consider using a 'constexpr' constant
macro 'DCD_IS_CHARMM' used to declare a constant; consider using a 'constexpr' constant
macro 'DCD_HAS_4DIMS' used to declare a constant; consider using a 'constexpr' constant
macro 'DCD_HAS_EXTRA_BLOCK' used to declare a constant; consider using a 'constexpr' constant
Version 1.1
Suite D4700
By making a contribution to this project, I certify …
> removed 2 type of clang-tidy errors in dcdformat.cpp

- avogadro/quantumio/orca.cpp
When reading an ORCA output file with an imaginary mode (which have an ***imaginary mode*** comment in the frequency line), the line and subsequent lines are skipped. This leads to an out-of-bounds access when reading normal modes, the IR spectrum or the Raman spectrum, as the indices read from the file are not verified.
Version 1.1
Suite D4700
have the right to submit it …
> Allow for reading imaginary vibrational frequencies in ORCA outputs.

- avogadro/quantumio/genericoutput.cpp
See https://discuss.avogadro.cc/t/impossible-to-read-molden-file/4924/
Version 1.1
Suite D4700
work …
> Add molden as a possible reader for generic `.out` files

- python/CMakeLists.txt
This is not part of the Python standard library, so it belongs in `SITEARCH`, not `STDARCH`
Version 1.1
Suite D4700
license and I have the right under that license …
> Fix Python module install dir

- avogadro/vtk/CMakeLists.txt
Without this, linking fails with
```
CMakeFiles/Vtk.dir/vtkAvogadroActor.cpp.o: in function `vtkAvogadroActor::RenderOpaqueGeometry(vtkViewport*)':
/usr/src/debug/avogadrolibs/avogadrolibs-1.98.0/avogadro/vtk/vtkAvogadroActor.cpp:56:(.text+0x27a): undefined reference to `glGetFloatv'
/usr/bin/ld: /usr/src/debug/avogadrolibs/avogadrolibs-1.98.0/avogadro/vtk/vtkAvogadroActor.cpp:57:(.text+0x28d): undefined reference to `glGetFloatv'
/usr/bin/ld: CMakeFiles/Vtk.dir/vtkAvogadroActor.cpp.o: in function `vtkAvogadroActor::RenderTranslucentPolygonalGeometry(vtkViewport*)':
/usr/src/debug/avogadrolibs/avogadrolibs-1.98.0/avogadro/vtk/vtkAvogadroActor.cpp:74:(.text+0x4af): undefined reference to `glGetFloatv'
/usr/bin/ld: /usr/src/debug/avogadrolibs/avogadrolibs-1.98.0/avogadro/vtk/vtkAvogadroActor …
```
> vtk: Add missing OpenGL link target

- .github/workflows/build_cmake.yml
- .github/workflows/build_m1.yml
- .github/workflows/build_wheels.yml
- .github/workflows/codacy.yml
- .github/workflows/codeql.yml
If a long build (e.g. Windows) starts up, but you find a typo, the concurrency should cancel the first build.
Overall, should boost throughput for builds / checks
Version 1.1
Suite D4700 …
> Add workflow concurrency - should stop builds during quick changes

- avogadro/io/fileformat.cpp
- avogadro/qtgui/fileformatdialog.cpp
> Make sure that filename validation occurs on save, not open

- avogadro/quantumio/orca.cpp
- avogadro/quantumio/orca.h
Probably just masks the underlying problem, but I need more examples https://discuss.avogadro.cc/t/cant-open-a-out-file-in-1-98-0/
Version 1.1
Suite D4700
license …
> Parsing orca output would crash when swapping orbitals

- avogadro/io/fileformat.cpp
- avogadro/qtgui/fileformatdialog.cpp
Something seems very off in the filter
Version 1.1
Suite D4700
work with modifications, whether …
> Revert validation of filenames.

- avogadro/io/pdbformat.cpp
- avogadro/qtplugins/select/select.cpp
Also adjust "select water" to better handle bonds to extra sites (e.g., H-O-H plus extra atom for water model)
Version 1.1
Suite D4700 …
> Fixup PDB reading with non-standard MD files (no element column)

- avogadro/qtplugins/forcefield/scripts/gfnff.py
> Fix GFN-FF energy - redirect GFN-FF output through a hack

- avogadro/io/cjsonformat.cpp
> Save partial charges and properly read them from CJSON

- avogadro/qtgui/hydrogentools.cpp
Figured I'd create this as a band-aid fix for https://github.com/OpenChemistry/avogadrolibs/issues/1492 (exact sequence of steps and screenshots included in that issue), just to avoid any crashes which could occur from someone accidentally triggering this pathway while editing something more complex. Still some more work to do to diagnose the real root cause behind the previously mentioned issue and https://github.com/OpenChemistry/avogadrolibs/issues/1478, but not sure how long that will take me to track down. 
Also happy to hold off on merging this possibly temporary fix if that sounds preferable, either way. 
Version 1.1
Suite D4700
Everyone is …
> Avoid segfaulting while manipulating carbon bonds/hydrogens

- avogadro/core/variant-inline.h
- avogadro/core/variant.h
Implicit conversion does not work for these types
Version 1.1
Suite D4700 …
> Add specialization for char* and MatrixXf types

- avogadro/core/atomutilities.h
- avogadro/core/coordinateblockgenerator.h
Fix #1476
Version 1.1
Suite D4700
by me, …
> Fix include of avogadrocoreexport.h

- avogadro/qtplugins/surfaces/surfacedialog.cpp
- avogadro/qtplugins/surfaces/surfacedialog.ui
- avogadro/qtplugins/surfaces/surfaces.cpp
> Make sure to automatically load the "Meshes" display type

- avogadro/qtplugins/propertytables/propertyview.cpp
- avogadro/qtplugins/propertytables/propertyview.h
Should add a context menu too
Version 1.1
Suite D4700
work with modifications, whether created in …
> Add initial support for copy from tables

- avogadro/qtgui/jsonwidget.cpp
> Fix for first item in ordered plugin dialog being empty

- avogadro/qtplugins/crystal/crystalscene.cpp
- avogadro/qtplugins/crystal/crystalscene.h
- avogadro/rendering/linestripgeometry.cpp
- avogadro/rendering/linestripgeometry.h
> Add red = a, blue = b, green = c color axes for unit cells

- avogadro/qtgui/scenepluginmodel.cpp
Fix #1529
Version 1.1
Suite D4700
by me, …
> Add "…" indicator for display types with settings

- avogadro/core/gaussiansettools.cpp
- avogadro/core/gaussiansettools.h
Rough timing shows significant speedup ~2x on C60
Version 1.1
Suite D4700 …
> Skip calculating points too far apart (e.g., negligible)

- python/CMakeLists.txt
- python/avogadro/__init__.py
- python/avogadro/cjson.py
- python/avogadro/connect.py
- python/io.cpp
> Add some additional classes including cjson and connect

- avogadro/qtplugins/plugindownloader/downloaderwidget.cpp
- avogadro/qtplugins/plugindownloader/downloaderwidget.h
> Add confirmation dialog to install with conda or pip

- avogadro/molequeue/inputgenerator.cpp
- avogadro/molequeue/inputgenerator.h
- avogadro/qtgui/interfacescript.cpp
- avogadro/qtgui/interfacescript.h
- avogadro/qtgui/pythonscript.cpp
- avogadro/qtgui/pythonscript.h
> Fixed typo in setDefaultPythonInterpretor()

- avogadro/qtgui/extensionplugin.h
- avogadro/qtgui/toolplugin.h
- avogadro/qtplugins/label/labeleditor.cpp
https://discuss.avogadro.cc/t/atom-label-tool-is-not-recognising-my-keyboard-input/5246?u=ghutchis
Version 1.1
Suite D4700 …
> Fix bug with incorrect Unicode characters added to labels

- avogadro/qtplugins/forcefield/forcefield.cpp
- avogadro/qtplugins/forcefield/forcefield.h
- avogadro/qtplugins/forcefield/obmmenergy.cpp
- avogadro/qtplugins/forcefield/obmmenergy.h
> Fix openbabel forcefield integration

- avogadro/calc/energymanager.cpp
- avogadro/qtplugins/forcefield/CMakeLists.txt
- avogadro/qtplugins/forcefield/forcefield.cpp
- avogadro/qtplugins/forcefield/obenergy.cpp
- avogadro/qtplugins/forcefield/obenergy.h
- avogadro/qtplugins/openbabel/openbabel.cpp
- cmake/FindOpenBabel3.cmake
> Add an optional calculator that links Open Babel

- avogadro/qtplugins/templatetool/CMakeLists.txt
> Fix wrong variable name

- avogadro/qtgui/sceneplugin.h
- avogadro/qtgui/scenepluginmodel.cpp
- avogadro/qtplugins/ballandstick/ballandstick.h
- avogadro/qtplugins/cartoons/cartoons.h
- avogadro/qtplugins/closecontacts/closecontacts.h
- avogadro/qtplugins/crystal/crystalscene.h
- avogadro/qtplugins/label/label.h
- avogadro/qtplugins/meshes/meshes.h
- avogadro/qtplugins/noncovalent/noncovalent.h
- avogadro/qtplugins/wireframe/wireframe.h
App would query if render plugins had options too early Added separate method (vs. checking for nullptr)
Fix #1617
Version 1.1
Suite D4700 …
> Fix crash at startup when opening a file from commandline

- avogadro/qtplugins/spacegroup/spacegroup.cpp
(e.g., if run on a primitive unit cell)
Version 1.1
Suite D4700
work with modifications, whether …
> Ask before re-perceiving a space group

- avogadro/io/pdbformat.cpp
> Fix bug reported in #1637 with mis-parsing selenium atoms in PDB

- avogadro/qtplugins/fetchpdb/fetchpdb.cpp
> Switch back to using PDB instead of MMTF format

- avogadro/core/atomutilities.cpp
Resolves hydrogen geometry reported on the forum
https://discuss.avogadro.cc/t/openbabel-adding-hydrogens-error-version-1-99-0-macos/5289?u=ghutchis
Version 1.1
Suite D4700
of my knowledge, is covered under an appropriate …
> Fix perception of amide nitrogens - should be sp2-like

- .github/workflows/build_cmake.yml
- .github/workflows/build_qt6.yml
> Fix MacOS builds using older runner (x86 only) for now

- .github/workflows/build_cmake.yml
> Try fixing Mac certificate signing again from base64 error

- avogadro/core/graph.cpp
Fixes bug from @aeonik
https://discuss.avogadro.cc/t/crash-when-dragging-atom-over-other-atom-to-create-bond/4964/18
Version 1.1
Suite D4700 …
> Add double-check for addEdge to prevent potential crash

- avogadro/qtplugins/openbabel/openbabel.cpp
> Switch import format default back to CJSON if found

- .github/workflows/build_cmake.yml
- .github/workflows/build_wheels.yml
- scripts/github-actions/repair-linux.sh
> Ensure MacOS binary packages are built

- .github/workflows/build_cmake.yml
Kill XProtect if running, as per:
https://github.com/actions/runner-images/issues/7522#issuecomment-1556766641
Version 1.1
Suite D4700 …
> Try to build Mac DMG more reliably

- avogadro/io/xyzformat.cpp
> Small patch to parsing XYZ trajectories to handle ORCA 6 separators

- avogadro/rendering/glrenderer.cpp
- avogadro/rendering/solid_first_fs.glsl
- avogadro/rendering/solidpipeline.cpp
- avogadro/rendering/solidpipeline.h
issue : #347 
Signed-off by : [permindersingh089@gmail.com](mailto:permindersingh089@gmail.com)
Version 1.1
Suite D4700 …
> Added fog as rendering options.

- avogadro/qtplugins/label/CMakeLists.txt
- avogadro/qtplugins/label/label.cpp
> Add support for atomic partial charge labels

- avogadro/quantumio/molden.cpp
- avogadro/quantumio/molden.h
https://discuss.avogadro.cc/t/support-for-molden-frequencies/6331
Version 1.1
Suite D4700
work with …
> Add initial support for reading molden frequencies

- avogadro/qtplugins/forcefield/obenergy.cpp
Should fix #1723
Version 1.1
Suite D4700 …
> Add BABEL_LIBDIR and BABEL_DATADIR to environment on Mac

- avogadro/qtplugins/cp2kinput/cp2kinputdialog.cpp
> cp2kinput improvements

- avogadro/io/xyzformat.cpp
> Initial support for reading charges and forces from extended XYZ

- avogadro/core/secondarystructure.cpp
- avogadro/rendering/cartoongeometry.cpp
- added 3-10 and pi helices
Version 1.1
Suite D4700
work with modifications, whether created in whole …
> ENH: Additional Secondary Structures

- avogadro/io/mdlformat.cpp
- avogadro/io/mdlformat.h
- avogadro/io/sdfformat.cpp
More work to do, including support for RDKit extensions
Version 1.1
Suite D4700
work with …
> Add basic support for v3000 molfiles, including for large molecules

- avogadro/qtplugins/manipulator/manipulatewidget.ui
- avogadro/qtplugins/manipulator/manipulator.cpp
- avogadro/qtplugins/manipulator/manipulator.h
Fix #1755 
Also allows rotating everything else if you want to fix the selection
Version 1.1
Suite D4700
license and I have the right under that license to submit …
> Fix manipulate dialog - rotate around origin, molecule center, selection center

- .github/workflows/build_qt6.yml
Also use mac-latest to try building Apple Silicon / universal
Version 1.1
Suite D4700
work with …
> Bumping to Qt 6.8 (latest LTS) for Mac and Windows builds

- avogadro/core/utilities.h
- avogadro/quantumio/molden.cpp
https://discuss.avogadro.cc/t/atoms-in-caps-in-molden-file-does-not-read-the-atoms/6465
Version 1.1
Suite D4700 …
> Handle upper-case [ATOMS] line in Molden files from Cfour

- avogadro/core/residue.cpp
Ran clang-format again
Version 1.1
Suite D4700
work with modifications, whether created in whole or …
> Fix residue not initializing id in default constructor

- avogadro/qtplugins/licorice/licorice.cpp
- avogadro/qtplugins/licorice/licorice.h
Probably should tune the radius too
Version 1.1
Suite D4700
work with modifications, whether created …
> Add opacity to the licorice rendering

- avogadro/qtplugins/licorice/licorice.cpp
- avogadro/qtplugins/vanderwaals/vanderwaals.cpp
The code needed to look up the layers for each atom correctly
Version 1.1
Suite D4700
work with …
> Fix a potential crash in the new translucent VdW & licorice code

- avogadro/qtplugins/forcefield/forcefield.cpp
- avogadro/qtplugins/forcefield/obenergy.cpp
Also make sure BABEL_DATADIR and BABEL_LIBDIR are set
Version 1.1
Suite D4700
work with …
> Initial work to fix potential crash on Windows

- avogadro/qtplugins/dipole/dipole.h
- avogadro/qtplugins/molecularproperties/molecularmodel.cpp
- avogadro/qtplugins/openbabel/obfileformat.cpp
- avogadro/quantumio/gaussianfchk.cpp
- avogadro/quantumio/gaussianfchk.h
Also fixes a few minor bugs
Version 1.1
Suite D4700
work with modifications, whether created in whole …
> Add HOMO and LUMO energies to properties

- .github/workflows/build_windows.yml
> More signpath

- avogadro/qtplugins/bondcentrictool/bondcentrictool.cpp
- avogadro/qtplugins/editor/editor.cpp
- avogadro/qtplugins/label/labeleditor.cpp
- avogadro/qtplugins/manipulator/manipulator.cpp
- avogadro/qtplugins/measuretool/measuretool.cpp
- avogadro/qtplugins/navigator/navigator.cpp
- avogadro/qtplugins/playertool/playertool.cpp
- avogadro/qtplugins/selectiontool/selectiontool.cpp
- avogadro/qtplugins/templatetool/templatetool.cpp
> Add Shortcut Keys to navigate/modify molecules (Issue #1794)

- avogadro/qtplugins/applycolors/applycolors.cpp
- avogadro/qtplugins/molecularproperties/molecularmodel.cpp
- avogadro/qtplugins/symmetry/symmetrywidget.cpp
- avogadro/quantumio/orca.cpp
- avogadro/quantumio/orca.h
> Support more molecular properties

- avogadro/core/gaussianset.cpp
- avogadro/core/gaussiansettools.cpp
- avogadro/core/gaussiansettools.h
> Implement g orbitals

- avogadro/qtgui/scriptloader.cpp
- avogadro/qtplugins/commandscripts/command.cpp
- avogadro/qtplugins/forcefield/CMakeLists.txt
- avogadro/qtplugins/forcefield/forcefield.cpp
- avogadro/qtplugins/forcefield/forcefield.h
- avogadro/qtplugins/quantuminput/quantuminput.cpp
Slight speedup and removes some debugging messages
Version 1.1
Suite D4700 …
> When possible, load script names from cache

- avogadro/qtplugins/cartoons/cartoons.cpp
- avogadro/qtplugins/insertdna/insertdna.cpp
> Add support for reading and rendering DNA / RNA backbones

- avogadro/io/xyzformat.cpp
- avogadro/qtplugins/openbabel/openbabel.cpp
- avogadro/qtplugins/propertytables/propertymodel.cpp
- avogadro/qtplugins/propertytables/propertymodel.h
- avogadro/qtplugins/propertytables/propertytables.cpp
- avogadro/qtplugins/propertytables/propertytables.h
- avogadro/qtplugins/propertytables/propertyview.cpp
> Add an initial conformer property window

- .github/workflows/build_cmake.yml
- .github/workflows/build_windows.yml
> Restore the default Windows build

- avogadro/quantumio/mopacaux.cpp
- avogadro/quantumio/mopacaux.h
> Parse more MOPAC aux properties including coordinates

- avogadro/qtgui/meshgenerator.cpp
- avogadro/qtgui/meshgenerator.h
> Explicitly use signed char in meshgenerator to avoid narrowing error on ARM

- avogadro/calc/chargemanager.cpp
- avogadro/calc/chargemodel.cpp
- avogadro/qtopengl/glwidget.cpp
- avogadro/qtopengl/glwidget.h
- avogadro/qtplugins/dipole/dipole.cpp
- avogadro/qtplugins/dipole/dipole.h
Fixes #1806 - prevents a race condition when rapidly updating the scene
Version 1.1
Suite D4700
work …
> Fix crashing with dipole moment

- avogadro/qtplugins/meshes/meshes.cpp
For the second mesh, we were still using old triangles array from the first mesh.
When we switch to the second mesh, we also fetch its triangles by calling `triangles2 = mesh->triangles();`. This ensures that the second mesh is rendered with its own vertices, normals, and triangle indices, not the first mesh's data.
Here's the result:
> Fixing Molecular orbital rendering with Flying Edges

- avogadro/io/cjsonformat.cpp
- avogadro/qtplugins/label/labeleditor.cpp
- avogadro/qtplugins/manipulator/manipulator.cpp
If nothing is selected or clicked, tools should fall back to rotate / pan
Version 1.1
Suite D4700 …
> Fix both the manipulate and label tool to rotate / navigate by default

- avogadro/calc/lennardjones.h
- avogadro/qtplugins/forcefield/forcefield.cpp
- avogadro/qtplugins/forcefield/scriptenergy.cpp
- avogadro/qtplugins/forcefield/scriptenergy.h
> Fix script energies

- avogadro/qtplugins/forcefield/forcefield.cpp
Fix #1601
Version 1.1
Suite D4700
by me, …
> Add progress bar for optimizations, including cancel

- avogadro/qtplugins/surfaces/surfaces.cpp
Fix #1582
Version 1.1
Suite D4700
by me, …
> Allow surface generation to be cancelled

- avogadro/qtplugins/surfaces/orbitals.cpp
- avogadro/quantumio/orca.cpp
Also fix the regex used for parsing orbital coefficients
Version 1.1
Suite D4700
work with …
> Ensure we get the right orbital energies (in eV) from ORCA

- avogadro/core/spacegroups.cpp
- avogadro/core/spacegroups.h
- avogadro/core/unitcell.h
- avogadro/qtplugins/spacegroup/spacegroup.cpp
- Move "fill unit cell" to the main menu for easy discovery
- Wrap any atoms at 1.0 fractional to 0.0 for convention
- Don't generate "all copies" by default (eventually we should have this as a separate command)
Version 1.1
Suite D4700
(b) The contribution is based upon previous work that, …
> Fixes for filling the unit cell

- avogadro/qtopengl/CMakeLists.txt
- cmake/AvogadroLibsConfig.cmake.in
The public glwidget.h header uses it, so the link must be public
Version 1.1
Suite D4700
work with …
> Link publicly against Qt6::OpenGLWidgets

- avogadro/quantumio/genericoutput.cpp
> Add xtbopt.log files (really XYZ) to the generic reader

- avogadro/qtplugins/quantuminput/CMakeLists.txt
- avogadro/qtplugins/surfaces/orbitals.cpp
> Avoid crash in orbitals when switching molecules

- .github/workflows/build_cmake.yml
- .github/workflows/build_linux.yml
- .github/workflows/build_qt6.yml
> Switch Linux release builds to Qt6

- tests/qtgui/CMakeLists.txt
> Only build MoleQueue tests when requested

- avogadro/qtplugins/vibrations/vibrationdialog.cpp
- avogadro/qtplugins/vibrations/vibrationmodel.cpp
Add a column to the left with the index of each normal mode in the table. This feature can be helpful for quickly identifying the mode for certain analyses.
Version 1.1
Suite D4700 …
> Add mode numbers to Vibrational Modes table

- avogadro/quantumio/gaussianfchk.cpp
- avogadro/quantumio/gaussianfchk.h
> Make sure Gaussian fchk orbitals are read with eV energies

- avogadro/qtplugins/apbs/apbsdialog.ui
- avogadro/qtplugins/spectra/spectradialog.ui
- scripts/extract-messages.sh
replace "..." with "…"
https://www.gnu.org/software/gettext/manual/html_node/xgettext-Invocation.html#index-_002d_002dcheck_002c-xgettext-option
Version 1.1
Suite D4700 …
> style(i18n): add --check=ellipsis-unicode for gettext and use unicode ellipsis

- avogadro/qtgui/CMakeLists.txt
- tests/qtgui/CMakeLists.txt
FindPythonInterp is deprecated since CMake 3.12
https://cmake.org/cmake/help/v3.12/module/FindPythonInterp.html
Version 1.1
Suite D4700 …
> build: replace FindPythonInterp with FindPython3

- python/CMakeLists.txt
- thirdparty/tinycolormap/CMakeLists.txt
CMake 4 drops support of 3.4 or earlier
note: FindPython is introduced in 3.12
https://cmake.org/cmake/help/v3.12/release/3.12.html#modules
Version 1.1
Suite D4700 …
> build: bump cmake_minimum_required

- avogadro/qtplugins/qtaim/qtaimengine.cpp
- avogadro/qtplugins/qtaim/qtaimengine.h
> Fix minor warning about "undef" layer caused by QTAIM changes

- tests/core/CMakeLists.txt
> test: enable spacegrouptest only if USE_SPGLIB is true

- avogadro/qtplugins/cp2kinput/cp2kinputdialog.cpp
- avogadro/qtplugins/cp2kinput/cp2kinputdialog.h
Only the both concerned enum are moved.
```
avogadrolibs-1.100.0/avogadro/qtplugins/cp2kinput/cp2kinputdialog.cpp:61:6: error: type ‘Avogadro::QtPlugins::BasisOption’ violates the C++ One Definition Rule [-Werror=odr]
61 | enum BasisOption
|      ^
avogadrolibs-1.100.0/work/avogadrolibs-1.100.0/avogadro/qtplugins/cp2kinput/cp2kinputdialog.cpp:40:6:
error: type ‘Avogadro::QtPlugins::CalculateOption’ violates the C++ One Definition Rule [-Werror=odr]
40 | enum CalculateOption
|      ^
```
Version 1.1
Suite D4700
Developer's …
> Fix ODR violations, move enums into class scope

- tests/core/CMakeLists.txt
- tests/core/atomtypertest.cpp
> fix: fix test suite names

- i18n/ka.po
At the moment weblate is locked due to conflict. <https://hosted.weblate.org/projects/avogadro/avogadrolibs/#alerts>
I followed
> 3. Add Weblate exported repository as a remote.
> git remote add weblate https://hosted.weblate.org/git/avogadro/avogadrolibs/ ; git remote update weblate
> 4. Merge Weblate changes and resolve any conflicts.
> git merge weblate/master
> 5. Rebase Weblate changes on top of upstream and resolve any conflicts.
> git rebase origin/master 
---
Version 1.1
Suite D4700
By …
> i18n: resolve conflict with weblate

- avogadro/qtplugins/constraints/constraintsextension.cpp
close #2134
Version 1.1
Suite D4700
by …
> fix: fix nullptr dereference

- avogadro/io/vaspformat.cpp
fix #2151
Version 1.1
Suite D4700
by me, …
> feat(Io): recognize CONTCAR and *.vasp as VASP geometry file

- tests/qtopengl/CMakeLists.txt
> fix(QtOpenGL): honor QT_VERSION

- avogadro/core/cube.cpp
Right now this is causing weird crashes with assignment operators
Version 1.1
Suite D4700
work with …
> Ignore the Mutex when deleting Cubes
